// L1-S11 時間表達進階
// 場景：歐寶需要告訴王阿嬤今天是星期幾，以及明天的洗澡安排。
import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L1_S11: ScenarioDef = {
  code: "L1-S11",
  level: Level.A1_BEGINNER,
  orderIndex: 11,
  title: "時間表達進階",
  titleI18n: {
    "zh-TW": "時間表達進階",
    th: "การบอกวันและเวลาขั้นสูง",
    vi: "Biểu đạt thời gian nâng cao",
    id: "Ungkapan Waktu Tingkat Lanjut",
  },
  estimatedMinutes: 25,
  prerequisiteCode: "L1-S10",
  hookContent: {
    storyTextI18n: {
      "zh-TW": "王阿嬤問歐寶今天是什麼日子，還有明天有沒有安排。歐寶需要學會說星期、今天、明天、昨天，才能跟阿嬤好好溝通……",
      th: "คุณยายหวังถามอ้าวเป่าว่าวันนี้เป็นวันอะไร และพรุ่งนี้มีนัดอะไรไหม อ้าวเป่าต้องเรียนรู้การพูดถึงวัน วันนี้ พรุ่งนี้ เมื่อวาน เพื่อสื่อสารกับยายได้ดี...",
      vi: "Bà Wang hỏi Aobao hôm nay là ngày mấy và ngày mai có lịch gì không. Aobao cần học cách nói ngày trong tuần, hôm nay, ngày mai, hôm qua để giao tiếp tốt với bà...",
      id: "Nenek Wang bertanya kepada Aobao hari apa sekarang dan apakah besok ada jadwal. Aobao perlu belajar menyebutkan hari, hari ini, besok, kemarin untuk berkomunikasi dengan baik bersama nenek...",
    },
  },
  mtcAlignment: { books: ["B1-L11"], topics: ["time", "schedule"] },
  vocabularies: [
    { hanzi: "今天", zhuyin: "ㄐㄧㄣ ㄊㄧㄢ", pinyin: "jīntiān", partOfSpeech: "n.", translations: { th: "วันนี้", en: "today" }, category: "time", tags: ["time"], difficulty: 1 },
    { hanzi: "明天", zhuyin: "ㄇㄧㄥˊ ㄊㄧㄢ", pinyin: "míngtiān", partOfSpeech: "n.", translations: { th: "พรุ่งนี้", en: "tomorrow" }, category: "time", tags: ["time"], difficulty: 1 },
    { hanzi: "昨天", zhuyin: "ㄗㄨㄛˊ ㄊㄧㄢ", pinyin: "zuótiān", partOfSpeech: "n.", translations: { th: "เมื่อวาน", en: "yesterday" }, category: "time", tags: ["time"], difficulty: 1 },
    { hanzi: "星期", zhuyin: "ㄒㄧㄥ ㄑㄧ", pinyin: "xīngqī", partOfSpeech: "n.", translations: { th: "วัน (ในสัปดาห์)", en: "day of the week" }, category: "time", tags: ["time"], difficulty: 1 },
    { hanzi: "星期三", zhuyin: "ㄒㄧㄥ ㄑㄧ ㄙㄢ", pinyin: "xīngqīsān", partOfSpeech: "n.", translations: { th: "วันพุธ", en: "Wednesday" }, category: "time", tags: ["time"], difficulty: 1 },
    { hanzi: "洗澡", zhuyin: "ㄒㄧˇ ㄗㄠˇ", pinyin: "xǐzǎo", partOfSpeech: "v.", translations: { th: "อาบน้ำ", en: "to bathe" }, category: "eldercare", tags: ["care", "hygiene"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "安排", zhuyin: "ㄢ ㄆㄞˊ", pinyin: "ānpái", partOfSpeech: "v/n.", translations: { th: "จัดการ / นัดหมาย", en: "to arrange/schedule" }, category: "daily", tags: ["schedule"], difficulty: 2 },
    { hanzi: "星期四", zhuyin: "ㄒㄧㄥ ㄑㄧ ㄙˋ", pinyin: "xīngqīsì", partOfSpeech: "n.", translations: { th: "วันพฤหัสบดี", en: "Thursday" }, category: "time", tags: ["time"], difficulty: 1 },
    { hanzi: "幾號", zhuyin: "ㄐㄧˇ ㄏㄠˋ", pinyin: "jǐ hào", partOfSpeech: "q.", translations: { th: "วันที่เท่าไหร่", en: "what date?" }, category: "time", tags: ["question", "time"], difficulty: 1 },
    { hanzi: "記得", zhuyin: "ㄐㄧˋ ˙ㄉㄜ", pinyin: "jìde", partOfSpeech: "v.", translations: { th: "จำได้", en: "to remember" }, category: "daily", tags: ["cognitive"], difficulty: 1 },
  ],
  dialogue: [
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿嬤", th: "คุณยายหวัง" },
      hanzi: "歐寶，今天是星期幾？",
      pinyin: "Ōubǎo, jīntiān shì xīngqī jǐ?",
      translationI18n: { th: "อ้าวเป่า วันนี้วันอะไร?" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿嬤，今天是星期三。",
      pinyin: "ā mā, jīntiān shì xīngqīsān.",
      translationI18n: { th: "คุณยาย วันนี้วันพุธค่ะ" },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿嬤", th: "คุณยายหวัง" },
      hanzi: "那明天是星期四，我要洗澡嗎？",
      pinyin: "nà míngtiān shì xīngqīsì, wǒ yào xǐzǎo ma?",
      translationI18n: { th: "งั้นพรุ่งนี้วันพฤหัส ยายต้องอาบน้ำไหม?" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "是的，明天星期四有安排洗澡。",
      pinyin: "shì de, míngtiān xīngqīsì yǒu ānpái xǐzǎo.",
      translationI18n: { th: "ใช่ค่ะ พรุ่งนี้วันพฤหัสมีนัดอาบน้ำค่ะ" },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿嬤", th: "คุณยายหวัง" },
      hanzi: "好，我記得了，謝謝你。",
      pinyin: "hǎo, wǒ jìde le, xièxiè nǐ.",
      translationI18n: { th: "ได้เลย ยายจำได้แล้ว ขอบคุณนะ" },
    },
  ],
  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 1,
      prompt: { symbol: "今天", hanzi: "今天", pinyin: "jīntiān" },
      options: [{ value: "วันนี้" }, { value: "พรุ่งนี้" }, { value: "เมื่อวาน" }, { value: "สัปดาห์นี้" }],
      answer: { value: "วันนี้" },
      explanationI18n: { "zh-TW": "「今天」= today = วันนี้", th: "「今天 jīntiān」= วันนี้" },
      skillsTrained: ["vocab", "reading"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 1,
      prompt: { audioUrl: "/api/audio/vocab/明天", instructionKey: "listenPickHanzi" },
      options: [{ value: "明天" }, { value: "今天" }, { value: "昨天" }, { value: "星期" }],
      answer: { value: "明天" },
      audioUrl: "/api/audio/vocab/明天",
      skillsTrained: ["listening", "vocab"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 1,
      prompt: { thai: "อาบน้ำ", instructionKey: "thaiToHanzi" },
      options: [{ value: "洗澡" }, { value: "洗手" }, { value: "吃飯" }, { value: "睡覺" }],
      answer: { value: "洗澡" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["今天是___四。"],
        sentencePinyin: "jīntiān shì ___ sì.",
        translationI18n: { th: "วันนี้วันพฤหัสบดี" },
        instructionKey: "fillBlank",
      },
      options: [{ value: "星期" }, { value: "明天" }, { value: "昨天" }, { value: "今天" }],
      answer: { value: "星期" },
      explanationI18n: { "zh-TW": "「星期四」= Thursday，「星期」+ 數字（一到日）。", th: "「星期四」= วันพฤหัสบดี ใช้「星期」+ ตัวเลข" },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["今天", "是", "星期三"],
        targetTranslationI18n: { th: "วันนี้วันพุธ" },
        instructionKey: "arrangeWords",
      },
      options: [{ value: "今天" }, { value: "是" }, { value: "星期三" }],
      answer: { value: ["今天", "是", "星期三"] },
      skillsTrained: ["grammar", "writing"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/dialogue/L1-S11/1",
        questionI18n: { "zh-TW": "明天阿嬤有什麼安排？", th: "พรุ่งนี้คุณยายมีนัดอะไร?" },
      },
      options: [{ value: "洗澡" }, { value: "吃藥" }, { value: "看醫生" }, { value: "量血壓" }],
      answer: { value: "洗澡" },
      audioUrl: "/api/audio/dialogue/L1-S11/1",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 2,
      prompt: {
        hanzi: "今天是星期三，明天有安排洗澡。",
        pinyin: "jīntiān shì xīngqīsān, míngtiān yǒu ānpái xǐzǎo.",
        audioUrl: "/api/audio/sentence/L1-S11-schedule",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 3,
      prompt: {
        targetHanzi: "明",
        pinyin: "míng",
        translationI18n: { th: "สว่าง / พรุ่งนี้ (ส่วนหนึ่ง)" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "明" },
      skillsTrained: ["writing"],
    },
  ],
};
