// L1-S04 認識身體部位
// 場景：王阿公指著頭說不舒服，歐寶需要知道身體部位詞彙才能溝通。
import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L1_S04: ScenarioDef = {
  code: "L1-S04",
  level: Level.A1_BEGINNER,
  orderIndex: 4,
  title: "認識身體部位",
  titleI18n: {
    "zh-TW": "認識身體部位",
    th: "รู้จักส่วนต่างๆ ของร่างกาย",
    vi: "Nhận biết các bộ phận cơ thể",
    id: "Mengenal Bagian Tubuh",
  },
  estimatedMinutes: 25,
  prerequisiteCode: "L1-S03",
  hookContent: {
    storyTextI18n: {
      "zh-TW": "歐寶第一次照顧王阿公。王阿公突然指著頭說很不舒服，但歐寶不知道那個漢字是什麼意思……",
      th: "วันแรกที่อ้าวเป่าดูแลคุณปู่หวัง คุณปู่ชี้ที่หัวแล้วบอกว่าไม่สบาย แต่อ้าวเป่าไม่รู้ว่าคำนั้นแปลว่าอะไร...",
      vi: "Ngày đầu tiên Aobao chăm sóc ông Wang. Ông chỉ vào đầu và nói không khỏe, nhưng Aobao không biết từ đó nghĩa là gì...",
      id: "Hari pertama Aobao merawat Kakek Wang. Kakek tiba-tiba menunjuk kepalanya dan bilang tidak nyaman, tapi Aobao tidak tahu arti kata itu...",
    },
  },
  mtcAlignment: { books: ["B1-L05"], topics: ["body-parts", "pain"] },
  vocabularies: [
    { hanzi: "頭", zhuyin: "ㄊㄡˊ", pinyin: "tóu", partOfSpeech: "n.", translations: { th: "หัว", en: "head" }, category: "body", tags: ["body", "pain"], difficulty: 1 },
    { hanzi: "眼睛", zhuyin: "ㄧㄢˇ ㄐㄧㄥ", pinyin: "yǎnjīng", partOfSpeech: "n.", translations: { th: "ตา", en: "eye" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "耳朵", zhuyin: "ㄦˇ ㄉㄨㄛ˙", pinyin: "ěrduo", partOfSpeech: "n.", translations: { th: "หู", en: "ear" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "嘴巴", zhuyin: "ㄗㄨㄟˇ ㄅㄚ", pinyin: "zuǐba", partOfSpeech: "n.", translations: { th: "ปาก", en: "mouth" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "手", zhuyin: "ㄕㄡˇ", pinyin: "shǒu", partOfSpeech: "n.", translations: { th: "มือ", en: "hand" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "腳", zhuyin: "ㄐㄧㄠˇ", pinyin: "jiǎo", partOfSpeech: "n.", translations: { th: "เท้า", en: "foot/leg" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "肚子", zhuyin: "ㄉㄨˋ ˙ㄗ", pinyin: "dùzi", partOfSpeech: "n.", translations: { th: "ท้อง", en: "belly/stomach" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "背", zhuyin: "ㄅㄟˋ", pinyin: "bèi", partOfSpeech: "n.", translations: { th: "หลัง", en: "back" }, category: "body", tags: ["body"], difficulty: 1 },
    { hanzi: "痛", zhuyin: "ㄊㄨㄥˋ", pinyin: "tòng", partOfSpeech: "adj.", translations: { th: "เจ็บ/ปวด", en: "painful/hurt" }, category: "symptom", tags: ["pain", "eldercare"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "哪裡", zhuyin: "ㄋㄚˇ ㄌㄧˇ", pinyin: "nǎlǐ", partOfSpeech: "pron.", translations: { th: "ที่ไหน", en: "where" }, category: "question", tags: ["question"], difficulty: 1 },
  ],
  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿公，您哪裡痛？",
      pinyin: "ā gōng, nín nǎlǐ tòng?",
      translationI18n: { th: "คุณปู่ ปวดที่ไหนครับ/ค่ะ?" },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿公", th: "คุณปู่หวัง" },
      hanzi: "我的頭很痛。",
      pinyin: "wǒ de tóu hěn tòng.",
      translationI18n: { th: "หัวของฉันปวดมาก" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "還有哪裡不舒服嗎？",
      pinyin: "hái yǒu nǎlǐ bù shūfu ma?",
      translationI18n: { th: "มีที่อื่นที่ไม่สบายอีกไหมครับ/ค่ะ?" },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿公", th: "คุณปู่หวัง" },
      hanzi: "我的手也痛。",
      pinyin: "wǒ de shǒu yě tòng.",
      translationI18n: { th: "มือของฉันก็ปวดด้วย" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "好，我去叫護士來看您。",
      pinyin: "hǎo, wǒ qù jiào hùshi lái kàn nín.",
      translationI18n: { th: "ได้เลย ฉันจะไปเรียกพยาบาลมาดูแลคุณปู่" },
    },
  ],
  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 1,
      prompt: { symbol: "頭", hanzi: "頭", pinyin: "tóu" },
      options: [{ value: "หัว" }, { value: "มือ" }, { value: "เท้า" }, { value: "หลัง" }],
      answer: { value: "หัว" },
      explanationI18n: { "zh-TW": "「頭」= head = หัว", th: "「頭 tóu」= หัว" },
      skillsTrained: ["vocab", "reading"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 1,
      prompt: { audioUrl: "/api/audio/vocab/痛", instructionKey: "listenPickHanzi" },
      options: [{ value: "痛" }, { value: "頭" }, { value: "手" }, { value: "腳" }],
      answer: { value: "痛" },
      audioUrl: "/api/audio/vocab/痛",
      skillsTrained: ["listening", "vocab"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 1,
      prompt: { thai: "ที่ไหน", instructionKey: "thaiToHanzi" },
      options: [{ value: "哪裡" }, { value: "這裡" }, { value: "那裡" }, { value: "哪個" }],
      answer: { value: "哪裡" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["您的", "___", "痛？"],
        sentencePinyin: "nín de ___ tòng?",
        translationI18n: { th: "คุณปู่ปวดที่___?" },
        instructionKey: "fillBlank",
      },
      options: [{ value: "哪裡" }, { value: "什麼" }, { value: "多少" }, { value: "幾個" }],
      answer: { value: "哪裡" },
      explanationI18n: { "zh-TW": "「您的哪裡痛？」用「哪裡」詢問身體的哪個部位。", th: "「您的哪裡痛」ใช้「哪裡」ถามว่าปวดส่วนไหนของร่างกาย" },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["我", "的", "頭", "很", "痛"],
        targetTranslationI18n: { th: "หัวของฉันปวดมาก" },
        instructionKey: "arrangeWords",
      },
      options: [{ value: "我" }, { value: "的" }, { value: "頭" }, { value: "很" }, { value: "痛" }],
      answer: { value: ["我", "的", "頭", "很", "痛"] },
      skillsTrained: ["grammar", "writing"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/dialogue/L1-S04/1",
        questionI18n: { "zh-TW": "王阿公哪裡痛？", th: "คุณปู่หวังปวดที่ไหน?" },
      },
      options: [{ value: "頭和手" }, { value: "腳和背" }, { value: "眼睛和耳朵" }, { value: "肚子" }],
      answer: { value: "頭和手" },
      audioUrl: "/api/audio/dialogue/L1-S04/1",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 2,
      prompt: {
        hanzi: "您哪裡痛？",
        pinyin: "nín nǎlǐ tòng?",
        audioUrl: "/api/audio/sentence/L1-S04-pain-query",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 3,
      prompt: {
        targetHanzi: "頭",
        pinyin: "tóu",
        translationI18n: { th: "หัว" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "頭" },
      skillsTrained: ["writing"],
    },
  ],
};
