// L1-S12 月底交班基礎
// 場景：歐寶輪班結束，需要向接班同事說明王阿公今天的狀況。
import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L1_S12: ScenarioDef = {
  code: "L1-S12",
  level: Level.A1_BEGINNER,
  orderIndex: 12,
  title: "交班基礎用語",
  titleI18n: {
    "zh-TW": "交班基礎用語",
    th: "คำพูดพื้นฐานสำหรับส่งเวร",
    vi: "Từ ngữ cơ bản khi bàn giao ca",
    id: "Kata-kata Dasar Serah Terima Shift",
  },
  estimatedMinutes: 30,
  prerequisiteCode: "L1-S11",
  hookContent: {
    storyTextI18n: {
      "zh-TW": "歐寶的白天班快結束了，她要把王阿公今天的狀況交接給接班的學姊。她需要學會怎麼說「平安」「吃飯了」「睡覺了」「沒事」……",
      th: "กะกลางวันของอ้าวเป่าใกล้จะหมดแล้ว เธอต้องส่งเวรให้พี่ที่มาแทน โดยบอกสถานการณ์ของคุณปู่หวังวันนี้ เธอต้องเรียนรู้คำว่า 'ปลอดภัยดี' 'ทานข้าวแล้ว' 'นอนหลับแล้ว' 'ไม่มีอะไร'...",
      vi: "Ca ngày của Aobao sắp kết thúc, cô cần bàn giao tình trạng của ông Wang hôm nay cho người tiếp ca. Cô cần học cách nói 'bình an', 'đã ăn', 'đã ngủ', 'không có gì'...",
      id: "Shift siang Aobao hampir selesai, dia perlu menyerahkan kondisi Kakek Wang hari ini kepada pengganti shift. Dia perlu belajar cara mengatakan 'aman', 'sudah makan', 'sudah tidur', 'tidak ada apa-apa'...",
    },
  },
  mtcAlignment: { books: ["B1-L12"], topics: ["handoff", "daily-care"] },
  vocabularies: [
    { hanzi: "平安", zhuyin: "ㄆㄧㄥˊ ㄢ", pinyin: "píng ān", partOfSpeech: "adj.", translations: { th: "ปลอดภัย/สบายดี", en: "safe and sound" }, category: "eldercare", tags: ["safety", "status"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "沒事", zhuyin: "ㄇㄟˊ ˙ㄕ", pinyin: "méishì", partOfSpeech: "exp.", translations: { th: "ไม่มีอะไร / ไม่เป็นไร", en: "nothing happened/it's fine" }, category: "daily", tags: ["reassurance"], difficulty: 1 },
    { hanzi: "吃飯", zhuyin: "ㄔ ㄈㄢˋ", pinyin: "chī fàn", partOfSpeech: "v.", translations: { th: "ทานข้าว", en: "to eat (meal)" }, category: "eldercare", tags: ["meal"], difficulty: 1 },
    { hanzi: "睡覺", zhuyin: "ㄕㄨㄟˋ ㄐㄧㄠˋ", pinyin: "shuì jiào", partOfSpeech: "v.", translations: { th: "นอนหลับ", en: "to sleep" }, category: "eldercare", tags: ["rest"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "換班", zhuyin: "ㄏㄨㄢˋ ㄅㄢ", pinyin: "huàn bān", partOfSpeech: "v.", translations: { th: "เปลี่ยนกะ", en: "shift change" }, category: "work", tags: ["work", "schedule"], difficulty: 2 },
    { hanzi: "正常", zhuyin: "ㄓㄥˋ ㄔㄤˊ", pinyin: "zhèngcháng", partOfSpeech: "adj.", translations: { th: "ปกติ", en: "normal" }, category: "status", tags: ["health", "status"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "狀況", zhuyin: "ㄓㄨㄤˋ ㄎㄨㄤˋ", pinyin: "zhuàngkuàng", partOfSpeech: "n.", translations: { th: "สภาพ / อาการ", en: "condition/situation" }, category: "eldercare", tags: ["health", "report"], difficulty: 2, isEldercareVocab: true },
    { hanzi: "注意", zhuyin: "ㄓㄨˋ ㄧˋ", pinyin: "zhùyì", partOfSpeech: "v.", translations: { th: "ระวัง / ใส่ใจ", en: "to pay attention/watch out" }, category: "work", tags: ["care", "alert"], difficulty: 1 },
    { hanzi: "交班", zhuyin: "ㄐㄧㄠ ㄅㄢ", pinyin: "jiāo bān", partOfSpeech: "v.", translations: { th: "ส่งเวร", en: "to hand over a shift" }, category: "work", tags: ["work", "handoff"], difficulty: 2, isEldercareVocab: true },
    { hanzi: "報告", zhuyin: "ㄅㄠˋ ㄍㄠˋ", pinyin: "bàogào", partOfSpeech: "v/n.", translations: { th: "รายงาน", en: "to report/report" }, category: "work", tags: ["work", "communication"], difficulty: 2 },
  ],
  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "學姊，我來交班，王阿公今天狀況報告。",
      pinyin: "xuéjiě, wǒ lái jiāo bān, Wáng ā gōng jīntiān zhuàngkuàng bàogào.",
      translationI18n: { th: "พี่คะ หนูมาส่งเวร รายงานอาการคุณปู่หวังวันนี้ค่ะ" },
    },
    {
      speaker: "colleague",
      speakerLabel: { "zh-TW": "林學姊", th: "พี่หลิน" },
      hanzi: "好，說吧。",
      pinyin: "hǎo, shuō ba.",
      translationI18n: { th: "โอเค บอกมาเลย" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿公今天平安，吃飯睡覺都正常，沒事。",
      pinyin: "ā gōng jīntiān píng ān, chī fàn shuì jiào dōu zhèngcháng, méishì.",
      translationI18n: { th: "คุณปู่วันนี้ปลอดภัยดีค่ะ ทานข้าวนอนหลับปกติ ไม่มีอะไร" },
    },
    {
      speaker: "colleague",
      speakerLabel: { "zh-TW": "林學姊", th: "พี่หลิน" },
      hanzi: "好，有沒有需要特別注意的？",
      pinyin: "hǎo, yǒu méiyǒu xūyào tèbié zhùyì de?",
      translationI18n: { th: "โอเค มีอะไรที่ต้องระวังเป็นพิเศษไหม?" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "下午說腳有點痛，請注意。",
      pinyin: "xiàwǔ shuō jiǎo yǒu diǎn tòng, qǐng zhùyì.",
      translationI18n: { th: "ตอนบ่ายบอกว่าเท้าเจ็บนิดหน่อย กรุณาระวังด้วยนะคะ" },
    },
  ],
  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 1,
      prompt: { symbol: "平安", hanzi: "平安", pinyin: "píng ān" },
      options: [{ value: "ปลอดภัย/สบายดี" }, { value: "เจ็บปวด" }, { value: "เหนื่อย" }, { value: "กังวล" }],
      answer: { value: "ปลอดภัย/สบายดี" },
      explanationI18n: { "zh-TW": "「平安」= safe and sound，養老院交班中常用來說明長輩狀況好。", th: "「平安 píng ān」= ปลอดภัย/สบายดี ใช้บอกสภาพผู้สูงอายุในการส่งเวร" },
      skillsTrained: ["vocab", "reading"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 1,
      prompt: { audioUrl: "/api/audio/vocab/睡覺", instructionKey: "listenPickHanzi" },
      options: [{ value: "睡覺" }, { value: "吃飯" }, { value: "平安" }, { value: "正常" }],
      answer: { value: "睡覺" },
      audioUrl: "/api/audio/vocab/睡覺",
      skillsTrained: ["listening", "vocab"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 1,
      prompt: { thai: "รายงาน", instructionKey: "thaiToHanzi" },
      options: [{ value: "報告" }, { value: "注意" }, { value: "交班" }, { value: "換班" }],
      answer: { value: "報告" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["阿公今天", "___", "，吃飯睡覺都正常。"],
        sentencePinyin: "ā gōng jīntiān ___, chī fàn shuì jiào dōu zhèngcháng.",
        translationI18n: { th: "คุณปู่วันนี้ปลอดภัยดี ทานข้าวนอนหลับปกติ" },
        instructionKey: "fillBlank",
      },
      options: [{ value: "平安" }, { value: "緊急" }, { value: "不對" }, { value: "害怕" }],
      answer: { value: "平安" },
      explanationI18n: { "zh-TW": "「平安」表示一切安好，是交班報告的常用詞。", th: "「平安」แปลว่าปลอดภัยสบายดี ใช้บ่อยในการส่งเวร" },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["阿公", "今天", "平安", "，", "沒事"],
        targetTranslationI18n: { th: "คุณปู่วันนี้ปลอดภัย ไม่มีอะไร" },
        instructionKey: "arrangeWords",
      },
      options: [{ value: "阿公" }, { value: "今天" }, { value: "平安" }, { value: "，" }, { value: "沒事" }],
      answer: { value: ["阿公", "今天", "平安", "，", "沒事"] },
      skillsTrained: ["grammar", "writing"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/dialogue/L1-S12/1",
        questionI18n: { "zh-TW": "王阿公今天的狀況怎麼樣？", th: "สภาพของคุณปู่หวังวันนี้เป็นอย่างไร?" },
      },
      options: [{ value: "平安正常" }, { value: "很嚴重" }, { value: "頭很暈" }, { value: "沒吃飯" }],
      answer: { value: "平安正常" },
      audioUrl: "/api/audio/dialogue/L1-S12/1",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 2,
      prompt: {
        hanzi: "阿公今天平安，吃飯睡覺都正常，沒事。",
        pinyin: "ā gōng jīntiān píng ān, chī fàn shuì jiào dōu zhèngcháng, méishì.",
        audioUrl: "/api/audio/sentence/L1-S12-handoff",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 3,
      prompt: {
        targetHanzi: "安",
        pinyin: "ān",
        translationI18n: { th: "สงบ / ปลอดภัย" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "安" },
      skillsTrained: ["writing"],
    },
  ],
};
