// L1-S10 求救基礎用語
// 場景：歐寶發現王阿公喊痛，需要呼叫護士學姊支援。
import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L1_S10: ScenarioDef = {
  code: "L1-S10",
  level: Level.A1_BEGINNER,
  orderIndex: 10,
  title: "求救基礎用語",
  titleI18n: {
    "zh-TW": "求救基礎用語",
    th: "คำพูดขอความช่วยเหลือเบื้องต้น",
    vi: "Từ ngữ cơ bản khi cần hỗ trợ",
    id: "Kata-kata Dasar Meminta Bantuan",
  },
  estimatedMinutes: 25,
  prerequisiteCode: "L1-S09",
  hookContent: {
    storyTextI18n: {
      "zh-TW": "歐寶在走廊聽到王阿公在房間裡大叫。她衝進去一看，阿公說腳很痛。歐寶需要馬上叫學姊和護士來幫忙……",
      th: "อ้าวเป่าได้ยินคุณปู่หวังร้องอยู่ในห้อง เธอวิ่งเข้าไปดู ปู่บอกว่าเท้าปวดมาก อ้าวเป่าต้องรีบเรียกพี่พยาบาลมาช่วย...",
      vi: "Aobao nghe thấy ông Wang kêu to trong phòng. Cô chạy vào xem, ông nói chân đau lắm. Aobao cần gọi chị y tá đến giúp ngay...",
      id: "Aobao mendengar Kakek Wang berteriak di kamar. Dia berlari masuk, Kakek bilang kakinya sangat sakit. Aobao harus segera memanggil kakak perawat untuk membantu...",
    },
  },
  mtcAlignment: { books: ["B1-L10"], topics: ["emergency", "help"] },
  vocabularies: [
    { hanzi: "學姊", zhuyin: "ㄒㄩㄝˊ ㄐㄧㄝˇ", pinyin: "xuéjiě", partOfSpeech: "n.", translations: { th: "พี่ผู้หญิง (รุ่นพี่)", en: "senior (female)" }, category: "person", tags: ["colleague"], difficulty: 1 },
    { hanzi: "急", zhuyin: "ㄐㄧˊ", pinyin: "jí", partOfSpeech: "adj.", translations: { th: "เร่งด่วน / รีบ", en: "urgent/hurry" }, category: "emergency", tags: ["emergency"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "痛", zhuyin: "ㄊㄨㄥˋ", pinyin: "tòng", partOfSpeech: "adj.", translations: { th: "เจ็บ/ปวด", en: "painful/hurt" }, category: "symptom", tags: ["pain"], difficulty: 1, isEldercareVocab: true },
    { hanzi: "幫忙", zhuyin: "ㄅㄤ ㄇㄤˊ", pinyin: "bāngmáng", partOfSpeech: "v.", translations: { th: "ช่วยด้วย", en: "to help" }, category: "emergency", tags: ["help"], difficulty: 1 },
    { hanzi: "快來", zhuyin: "ㄎㄨㄞˋ ㄌㄞˊ", pinyin: "kuài lái", partOfSpeech: "exp.", translations: { th: "รีบมาเร็ว", en: "come quickly" }, category: "emergency", tags: ["emergency"], difficulty: 1 },
    { hanzi: "一下", zhuyin: "ㄧ ㄒㄧㄚˋ", pinyin: "yīxià", partOfSpeech: "adv.", translations: { th: "สักครู่ / ซักหน่อย", en: "a moment/quickly" }, category: "daily", tags: ["time"], difficulty: 1 },
    { hanzi: "不對", zhuyin: "ㄅㄨˋ ㄉㄨㄟˋ", pinyin: "bú duì", partOfSpeech: "exp.", translations: { th: "ไม่ถูกต้อง / ไม่ใช่", en: "not right/wrong" }, category: "daily", tags: ["expression"], difficulty: 1 },
    { hanzi: "需要", zhuyin: "ㄒㄩ ㄧㄠˋ", pinyin: "xūyào", partOfSpeech: "v.", translations: { th: "ต้องการ", en: "to need" }, category: "daily", tags: ["need"], difficulty: 1 },
    { hanzi: "馬上", zhuyin: "ㄇㄚˇ ㄕㄤˋ", pinyin: "mǎshàng", partOfSpeech: "adv.", translations: { th: "ทันที", en: "immediately" }, category: "daily", tags: ["time"], difficulty: 1 },
    { hanzi: "怎麼了", zhuyin: "ㄗㄣˇ ㄇㄜ˙ ˙ㄌㄜ", pinyin: "zěnme le", partOfSpeech: "exp.", translations: { th: "เป็นอะไรไป / ทำไม", en: "what happened?" }, category: "question", tags: ["question"], difficulty: 1 },
  ],
  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "學姊！學姊！快來，需要幫忙！",
      pinyin: "xuéjiě! xuéjiě! kuài lái, xūyào bāngmáng!",
      translationI18n: { th: "พี่! พี่! รีบมาเร็ว ต้องการความช่วยเหลือ!" },
    },
    {
      speaker: "colleague",
      speakerLabel: { "zh-TW": "林學姊", th: "พี่หลิน" },
      hanzi: "怎麼了？發生什麼事？",
      pinyin: "zěnme le? fāshēng shénme shì?",
      translationI18n: { th: "เป็นอะไรไป? เกิดอะไรขึ้น?" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "王阿公說腳很痛，是緊急嗎？",
      pinyin: "Wáng ā gōng shuō jiǎo hěn tòng, shì jǐnjí ma?",
      translationI18n: { th: "คุณปู่หวังบอกว่าเท้าปวดมาก เป็นเหตุฉุกเฉินไหม?" },
    },
    {
      speaker: "colleague",
      speakerLabel: { "zh-TW": "林學姊", th: "พี่หลิน" },
      hanzi: "我馬上去看一下。你去叫護士。",
      pinyin: "wǒ mǎshàng qù kàn yīxià. nǐ qù jiào hùshi.",
      translationI18n: { th: "ฉันจะไปดูทันที แกไปเรียกพยาบาลมาด้วยนะ" },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "好的，我馬上去！",
      pinyin: "hǎo de, wǒ mǎshàng qù!",
      translationI18n: { th: "ได้เลย หนูไปทันที!" },
    },
  ],
  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 1,
      prompt: { symbol: "急", hanzi: "急", pinyin: "jí" },
      options: [{ value: "เร่งด่วน" }, { value: "ช้าๆ" }, { value: "เงียบ" }, { value: "สบาย" }],
      answer: { value: "เร่งด่วน" },
      explanationI18n: { "zh-TW": "「急」= urgent/hurry = เร่งด่วน/รีบ", th: "「急 jí」= เร่งด่วน/รีบ" },
      skillsTrained: ["vocab", "reading"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 1,
      prompt: { audioUrl: "/api/audio/vocab/幫忙", instructionKey: "listenPickHanzi" },
      options: [{ value: "幫忙" }, { value: "護士" }, { value: "急" }, { value: "馬上" }],
      answer: { value: "幫忙" },
      audioUrl: "/api/audio/vocab/幫忙",
      skillsTrained: ["listening", "vocab"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 1,
      prompt: { thai: "ทันที", instructionKey: "thaiToHanzi" },
      options: [{ value: "馬上" }, { value: "一下" }, { value: "快來" }, { value: "需要" }],
      answer: { value: "馬上" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["我___去叫護士！"],
        sentencePinyin: "wǒ ___ qù jiào hùshi!",
        translationI18n: { th: "หนูจะไปเรียกพยาบาลทันที!" },
        instructionKey: "fillBlank",
      },
      options: [{ value: "馬上" }, { value: "一下" }, { value: "需要" }, { value: "慢慢" }],
      answer: { value: "馬上" },
      explanationI18n: { "zh-TW": "「馬上」= 立刻、立即，表示非常緊迫的行動。", th: "「馬上」= ทันที แสดงความเร่งด่วน" },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["學姊", "！", "快來", "，", "需要", "幫忙"],
        targetTranslationI18n: { th: "พี่! รีบมา ต้องการความช่วยเหลือ!" },
        instructionKey: "arrangeWords",
      },
      options: [{ value: "學姊" }, { value: "！" }, { value: "快來" }, { value: "，" }, { value: "需要" }, { value: "幫忙" }],
      answer: { value: ["學姊", "！", "快來", "，", "需要", "幫忙"] },
      skillsTrained: ["grammar", "writing"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/dialogue/L1-S10/1",
        questionI18n: { "zh-TW": "歐寶要學姊做什麼？", th: "อ้าวเป่าให้พี่หลินทำอะไร?" },
      },
      options: [{ value: "快來幫忙" }, { value: "打電話" }, { value: "叫醫生" }, { value: "量血壓" }],
      answer: { value: "快來幫忙" },
      audioUrl: "/api/audio/dialogue/L1-S10/1",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 2,
      prompt: {
        hanzi: "學姊！快來，需要幫忙！",
        pinyin: "xuéjiě! kuài lái, xūyào bāngmáng!",
        audioUrl: "/api/audio/sentence/L1-S10-call-help",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 3,
      prompt: {
        targetHanzi: "急",
        pinyin: "jí",
        translationI18n: { th: "เร่งด่วน" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "急" },
      skillsTrained: ["writing"],
    },
  ],
};
