// L2-S04 翻身協助
//
// 場景:歐寶協助臥床的趙阿嬤翻身,避免褥瘡。要清楚說「左邊」「右邊」,
// 動作慢、確認阿嬤舒服。

import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L2_S04: ScenarioDef = {
  code: "L2-S04",
  level: Level.A2_BASIC,
  orderIndex: 4,
  title: "翻身協助",
  titleI18n: {
    "zh-TW": "翻身協助",
    th: "ช่วยพลิกตัวบนเตียง",
    vi: "Hỗ trợ trở mình trên giường",
    id: "Bantuan membalikkan badan di tempat tidur",
  },
  estimatedMinutes: 30,
  prerequisiteCode: "L2-S03",
  mtcAlignment: {
    books: ["B2-L01", "B2-L08", "B2-L09"],
    topics: ["direction", "body-position", "polite-instruction"],
  },
  hookContent: {
    storyTextI18n: {
      "zh-TW":
        "趙阿嬤臥床很久了,每兩個小時要幫她翻身一次,避免褥瘡。歐寶要先告訴阿嬤「我要幫您翻身了」,動作放慢,問阿嬤左邊好還是右邊好。",
      th: "คุณยายเจ้านอนเตียงมานานแล้ว ต้องพลิกตัวให้ทุก 2 ชั่วโมงเพื่อกันแผลกดทับ โอบาวต้องบอกคุณยายก่อนว่า「ฉันจะพลิกตัวให้นะคะ」 ทำช้า ๆ และถามว่าจะตะแคงซ้ายหรือขวา",
      vi: "Bà Triệu đã nằm giường lâu, cứ 2 tiếng phải trở mình một lần để tránh loét tì đè. Aobao cần báo trước, làm chậm, hỏi bà thích nghiêng trái hay phải.",
      id: "Nenek Zhao sudah lama berbaring, setiap 2 jam harus dibalik untuk mencegah luka tekan. Aobao perlu memberi tahu dulu, gerakan pelan, tanya nenek mau miring kiri atau kanan.",
    },
  },

  vocabularies: [
    {
      hanzi: "翻身",
      zhuyin: "ㄈㄢ ㄕㄣ",
      pinyin: "fān shēn",
      partOfSpeech: "v.",
      translations: { th: "พลิกตัว", en: "to turn over" },
      category: "eldercare",
      tags: ["essential", "eldercare", "personal-care"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "側身",
      zhuyin: "ㄘㄜˋ ㄕㄣ",
      pinyin: "cè shēn",
      partOfSpeech: "v.",
      translations: { th: "ตะแคง", en: "to lie on one's side" },
      category: "eldercare",
      tags: ["essential", "eldercare", "personal-care"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "左邊",
      zhuyin: "ㄗㄨㄛˇ ㄅㄧㄢ",
      pinyin: "zuǒ biān",
      partOfSpeech: "n.",
      translations: { th: "ด้านซ้าย", en: "left side" },
      category: "direction",
      tags: ["essential", "direction"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L09" },
    },
    {
      hanzi: "右邊",
      zhuyin: "ㄧㄡˋ ㄅㄧㄢ",
      pinyin: "yòu biān",
      partOfSpeech: "n.",
      translations: { th: "ด้านขวา", en: "right side" },
      category: "direction",
      tags: ["essential", "direction"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L09" },
    },
    {
      hanzi: "慢一點",
      zhuyin: "ㄇㄢˋ ㄧˋ ㄉㄧㄢˇ",
      pinyin: "màn yīdiǎn",
      partOfSpeech: "phrase",
      translations: { th: "ช้าหน่อย", en: "a little slower" },
      category: "instruction",
      tags: ["essential", "eldercare"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L01" },
    },
    {
      hanzi: "痛",
      zhuyin: "ㄊㄨㄥˋ",
      pinyin: "tòng",
      partOfSpeech: "adj.",
      translations: { th: "เจ็บ / ปวด", en: "painful" },
      category: "medical",
      tags: ["essential", "eldercare", "medical"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "床",
      zhuyin: "ㄔㄨㄤˊ",
      pinyin: "chuáng",
      partOfSpeech: "n.",
      translations: { th: "เตียง", en: "bed" },
      category: "noun",
      tags: ["essential", "eldercare"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L08" },
    },
    {
      hanzi: "枕頭",
      zhuyin: "ㄓㄣˇ ㄊㄡˊ",
      pinyin: "zhěntou",
      partOfSpeech: "n.",
      translations: { th: "หมอน", en: "pillow" },
      category: "eldercare",
      tags: ["essential", "eldercare"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "棉被",
      zhuyin: "ㄇㄧㄢˊ ㄅㄟˋ",
      pinyin: "miánbèi",
      partOfSpeech: "n.",
      translations: { th: "ผ้านวม / ผ้าห่ม", en: "comforter / quilt" },
      category: "eldercare",
      tags: ["essential", "eldercare"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "不要動",
      zhuyin: "ㄅㄨˊ ㄧㄠˋ ㄉㄨㄥˋ",
      pinyin: "bùyào dòng",
      partOfSpeech: "phrase",
      translations: { th: "อย่าขยับ", en: "don't move" },
      category: "instruction",
      tags: ["essential", "eldercare", "safety"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L03" },
    },
  ],

  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿嬤,我要幫您翻身了。",
      pinyin: "ā mà, wǒ yào bāng nín fān shēn le.",
      translationI18n: {
        th: "คุณยายคะ ฉันจะพลิกตัวให้นะคะ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "趙阿嬤", th: "คุณยายเจ้า" },
      hanzi: "好,我準備好了。",
      pinyin: "hǎo, wǒ zhǔnbèi hǎo le.",
      translationI18n: {
        th: "ดี ฉันพร้อมแล้ว",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "您要側左邊還是右邊?",
      pinyin: "nín yào cè zuǒ biān háishì yòu biān?",
      translationI18n: {
        th: "อยากตะแคงซ้ายหรือขวาคะ?",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "趙阿嬤", th: "คุณยายเจ้า" },
      hanzi: "左邊。慢一點,我有點痛。",
      pinyin: "zuǒ biān. màn yīdiǎn, wǒ yǒu diǎn tòng.",
      translationI18n: {
        th: "ซ้าย ช้าหน่อยนะ เจ็บนิดหน่อย",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "好的,我會慢慢來。我幫您墊枕頭。",
      pinyin: "hǎo de, wǒ huì mànman lái. wǒ bāng nín diàn zhěntou.",
      translationI18n: {
        th: "ได้ค่ะ จะค่อย ๆ ทำ ฉันจะช่วยรองหมอนให้",
      },
    },
  ],

  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 2,
      prompt: { symbol: "翻身", hanzi: "翻身", pinyin: "fān shēn" },
      options: [
        { value: "พลิกตัว" },
        { value: "นอน" },
        { value: "ลุก" },
        { value: "นั่ง" },
      ],
      answer: { value: "พลิกตัว" },
      skillsTrained: ["vocab", "eldercare"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/vocab/左邊",
        instructionKey: "listenPickHanzi",
      },
      options: [
        { value: "左邊" },
        { value: "右邊" },
        { value: "上面" },
        { value: "下面" },
      ],
      answer: { value: "左邊" },
      audioUrl: "/api/audio/vocab/左邊",
      skillsTrained: ["listening"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 2,
      prompt: { thai: "ช้าหน่อย", instructionKey: "thaiToHanzi" },
      options: [
        { value: "慢一點" },
        { value: "快一點" },
        { value: "等一下" },
        { value: "別動" },
      ],
      answer: { value: "慢一點" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["您", "要", "側", "___", "邊?"],
        sentencePinyin: "nín yào cè ___ biān?",
        translationI18n: { th: "อยากตะแคงด้าน ___ ?" },
        instructionKey: "fillBlank",
      },
      options: [
        { value: "左" },
        { value: "下" },
        { value: "後" },
        { value: "前" },
      ],
      answer: { value: "左" },
      explanationI18n: {
        "zh-TW": "「左邊 / 右邊」是位置詞;翻身一定要先確認方向。",
        th: "「左邊 / 右邊」เป็นคำบอกตำแหน่ง — ก่อนพลิกตัวต้องถามทิศทาง",
      },
      skillsTrained: ["grammar", "direction"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["我", "要", "幫", "您", "翻身"],
        targetTranslationI18n: { th: "ฉันจะพลิกตัวให้คุณ" },
        instructionKey: "arrangeWords",
      },
      options: [
        { value: "我" },
        { value: "要" },
        { value: "幫" },
        { value: "您" },
        { value: "翻身" },
      ],
      answer: { value: ["我", "要", "幫", "您", "翻身"] },
      skillsTrained: ["grammar", "polite"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/dialogue/L2-S04/3",
        questionI18n: {
          "zh-TW": "趙阿嬤想往哪邊翻?她有什麼感覺?",
          th: "คุณยายเจ้าต้องการตะแคงด้านไหน? รู้สึกอย่างไร?",
        },
      },
      options: [
        { value: "左邊,有點痛" },
        { value: "右邊,還好" },
        { value: "左邊,不痛" },
        { value: "右邊,很累" },
      ],
      answer: { value: "左邊,有點痛" },
      audioUrl: "/api/audio/dialogue/L2-S04/3",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 3,
      prompt: {
        hanzi: "阿嬤,我要幫您翻身了。慢一點,別動。",
        pinyin: "ā mà, wǒ yào bāng nín fān shēn le. màn yīdiǎn, bié dòng.",
        audioUrl: "/api/audio/dialogue/L2-S04/0",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking", "eldercare"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 4,
      prompt: {
        targetHanzi: "翻",
        pinyin: "fān",
        translationI18n: { th: "พลิก" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "翻" },
      skillsTrained: ["writing"],
    },
  ],
};
