// L2-S03 換尿布(基礎)
//
// 場景:歐寶第一次幫陳阿嬤換尿布。重點是尊重隱私 + 安撫話術 + 動作說明。

import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L2_S03: ScenarioDef = {
  code: "L2-S03",
  level: Level.A2_BASIC,
  orderIndex: 3,
  title: "換尿布(基礎)",
  titleI18n: {
    "zh-TW": "換尿布(基礎)",
    th: "เปลี่ยนผ้าอ้อม (พื้นฐาน)",
    vi: "Thay tã (cơ bản)",
    id: "Mengganti popok (dasar)",
  },
  estimatedMinutes: 35,
  prerequisiteCode: "L2-S02",
  mtcAlignment: {
    books: ["B2-L09", "B2-L10", "B2-L11", "B2-L12"],
    topics: ["polite-request", "comfort", "personal-care"],
  },
  hookContent: {
    storyTextI18n: {
      "zh-TW":
        "陳阿嬤需要換尿布了。歐寶第一次幫她換,要尊重阿嬤的隱私,動作輕柔,並用「不好意思」「我來幫您」這類禮貌話術。",
      th: "คุณยายเฉินต้องเปลี่ยนผ้าอ้อมแล้ว วันนี้โอบาวเปลี่ยนให้เป็นครั้งแรก ต้องเคารพความเป็นส่วนตัวของคุณยาย เคลื่อนไหวอย่างนุ่มนวล และใช้คำพูดสุภาพ เช่น 「ขอโทษค่ะ」「ฉันจะช่วยคุณยายเอง」",
      vi: "Bà Trần cần thay tã. Lần đầu Aobao thay cho bà, phải tôn trọng riêng tư, động tác nhẹ nhàng, dùng lời lẽ lịch sự như 「xin lỗi」「để tôi giúp」.",
      id: "Nenek Chen perlu diganti popoknya. Aobao baru pertama kali menggantikan, harus menghargai privasi, gerakan lembut, gunakan kalimat sopan seperti 「maaf」「saya bantu」.",
    },
  },

  vocabularies: [
    {
      hanzi: "等一下",
      zhuyin: "ㄉㄥˇ ㄧˊ ㄒㄧㄚˋ",
      pinyin: "děng yíxià",
      partOfSpeech: "phrase",
      translations: { th: "รอสักครู่", en: "wait a moment" },
      category: "phrase",
      tags: ["essential", "polite"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L09" },
    },
    {
      hanzi: "馬上",
      zhuyin: "ㄇㄚˇ ㄕㄤˋ",
      pinyin: "mǎshàng",
      partOfSpeech: "adv.",
      translations: { th: "ทันที", en: "right away" },
      category: "adverb",
      tags: ["essential", "time"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L09" },
    },
    {
      hanzi: "不好意思",
      zhuyin: "ㄅㄨˋ ㄏㄠˇ ㄧˋ ㄙ˙",
      pinyin: "bùhǎo yìsi",
      partOfSpeech: "phrase",
      translations: { th: "ขอโทษ / เกรงใจ", en: "excuse me / I'm sorry" },
      category: "polite",
      tags: ["essential", "polite", "eldercare"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L10" },
    },
    {
      hanzi: "沒關係",
      zhuyin: "ㄇㄟˊ ㄍㄨㄢ ㄒㄧˋ",
      pinyin: "méi guānxi",
      partOfSpeech: "phrase",
      translations: { th: "ไม่เป็นไร", en: "it's OK / no worries" },
      category: "polite",
      tags: ["essential", "polite"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L10" },
    },
    {
      hanzi: "幫忙",
      zhuyin: "ㄅㄤ ㄇㄤˊ",
      pinyin: "bāngmáng",
      partOfSpeech: "v.",
      translations: { th: "ช่วยเหลือ", en: "to help" },
      category: "verb",
      tags: ["essential"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L10" },
    },
    {
      hanzi: "乾淨",
      zhuyin: "ㄍㄢ ㄐㄧㄥˋ",
      pinyin: "gānjìng",
      partOfSpeech: "adj.",
      translations: { th: "สะอาด", en: "clean" },
      category: "adjective",
      tags: ["essential", "hygiene"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L11" },
    },
    {
      hanzi: "舒服",
      zhuyin: "ㄕㄨ ㄈㄨ˙",
      pinyin: "shūfu",
      partOfSpeech: "adj.",
      translations: { th: "สบาย", en: "comfortable" },
      category: "adjective",
      tags: ["essential", "feeling"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L12" },
    },
    {
      hanzi: "尿布",
      zhuyin: "ㄋㄧㄠˋ ㄅㄨˋ",
      pinyin: "niàobù",
      partOfSpeech: "n.",
      translations: { th: "ผ้าอ้อม", en: "diaper" },
      category: "eldercare",
      tags: ["essential", "eldercare", "personal-care"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "擦",
      zhuyin: "ㄘㄚ",
      pinyin: "cā",
      partOfSpeech: "v.",
      translations: { th: "เช็ด", en: "to wipe" },
      category: "verb",
      tags: ["essential", "eldercare", "personal-care"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "屁股",
      zhuyin: "ㄆㄧˋ ㄍㄨ˙",
      pinyin: "pìgu",
      partOfSpeech: "n.",
      translations: { th: "ก้น", en: "buttocks" },
      category: "body",
      tags: ["essential", "eldercare", "body"],
      difficulty: 2,
      isEldercareVocab: true,
    },
  ],

  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿嬤,不好意思,我來幫您換尿布。",
      pinyin: "ā mà, bùhǎo yìsi, wǒ lái bāng nín huàn niàobù.",
      translationI18n: {
        th: "คุณยายคะ ขอโทษนะคะ ฉันจะมาช่วยเปลี่ยนผ้าอ้อมให้ค่ะ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "陳阿嬤", th: "คุณยายเฉิน" },
      hanzi: "好,謝謝你。",
      pinyin: "hǎo, xièxie nǐ.",
      translationI18n: {
        th: "ดี ขอบคุณนะ",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "請等一下,我馬上幫您擦乾淨。",
      pinyin: "qǐng děng yíxià, wǒ mǎshàng bāng nín cā gānjìng.",
      translationI18n: {
        th: "รอสักครู่ค่ะ ฉันจะช่วยเช็ดให้สะอาดทันที",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "好了,現在舒服多了吧?",
      pinyin: "hǎo le, xiànzài shūfu duō le ba?",
      translationI18n: {
        th: "เสร็จแล้วค่ะ ตอนนี้สบายขึ้นมากแล้วใช่ไหมคะ?",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "陳阿嬤", th: "คุณยายเฉิน" },
      hanzi: "嗯,舒服。謝謝你的幫忙。",
      pinyin: "ǹ, shūfu. xièxie nǐ de bāngmáng.",
      translationI18n: {
        th: "อืม สบาย ขอบคุณที่ช่วย",
      },
    },
  ],

  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 2,
      prompt: { symbol: "舒服", hanzi: "舒服", pinyin: "shūfu" },
      options: [
        { value: "สบาย" },
        { value: "เจ็บ" },
        { value: "เหนื่อย" },
        { value: "ปวด" },
      ],
      answer: { value: "สบาย" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/vocab/尿布",
        instructionKey: "listenPickHanzi",
      },
      options: [
        { value: "尿布" },
        { value: "毛巾" },
        { value: "衣服" },
        { value: "棉被" },
      ],
      answer: { value: "尿布" },
      audioUrl: "/api/audio/vocab/尿布",
      skillsTrained: ["listening", "eldercare"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 2,
      prompt: { thai: "ขอโทษ / เกรงใจ", instructionKey: "thaiToHanzi" },
      options: [
        { value: "不好意思" },
        { value: "謝謝" },
        { value: "對不起" },
        { value: "麻煩" },
      ],
      answer: { value: "不好意思" },
      skillsTrained: ["vocab", "polite"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["我", "來", "___", "您", "換", "尿布"],
        sentencePinyin: "wǒ lái ___ nín huàn niàobù",
        translationI18n: { th: "ฉันจะมา ___ เปลี่ยนผ้าอ้อมให้คุณ" },
        instructionKey: "fillBlank",
      },
      options: [
        { value: "幫" },
        { value: "請" },
        { value: "看" },
        { value: "等" },
      ],
      answer: { value: "幫" },
      explanationI18n: {
        "zh-TW": "「我來幫您 + V」是禮貌的主動承擔句型,常用於照護工作。",
        th: "「我來幫您 + V」เป็นรูปประโยคสุภาพแสดงความตั้งใจช่วย ใช้บ่อยในการดูแลผู้สูงอายุ",
      },
      skillsTrained: ["grammar", "polite"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["請", "等一下", ",", "我", "馬上", "來"],
        targetTranslationI18n: { th: "รอสักครู่ ฉันจะมาทันที" },
        instructionKey: "arrangeWords",
      },
      options: [
        { value: "請" },
        { value: "等一下" },
        { value: "," },
        { value: "我" },
        { value: "馬上" },
        { value: "來" },
      ],
      answer: { value: ["請", "等一下", ",", "我", "馬上", "來"] },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 3,
      prompt: {
        audioUrl: "/api/audio/dialogue/L2-S03/3",
        questionI18n: {
          "zh-TW": "歐寶最後問阿嬤什麼?",
          th: "สุดท้ายโอบาวถามคุณยายว่าอะไร?",
        },
      },
      options: [
        { value: "現在舒服多了吧?" },
        { value: "您餓了嗎?" },
        { value: "想喝水嗎?" },
        { value: "可以走路嗎?" },
      ],
      answer: { value: "現在舒服多了吧?" },
      audioUrl: "/api/audio/dialogue/L2-S03/3",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 3,
      prompt: {
        hanzi: "阿嬤,不好意思,我來幫您換尿布。",
        pinyin: "ā mà, bùhǎo yìsi, wǒ lái bāng nín huàn niàobù.",
        audioUrl: "/api/audio/dialogue/L2-S03/0",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking", "polite"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 4,
      prompt: {
        targetHanzi: "幫",
        pinyin: "bāng",
        translationI18n: { th: "ช่วย" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "幫" },
      skillsTrained: ["writing"],
    },
  ],
};
