// L2-S06 上廁所協助
//
// 場景:歐寶協助行動不便的劉阿嬤上廁所,從房間扶到廁所,確保安全與隱私。

import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L2_S06: ScenarioDef = {
  code: "L2-S06",
  level: Level.A2_BASIC,
  orderIndex: 6,
  title: "上廁所協助",
  titleI18n: {
    "zh-TW": "上廁所協助",
    th: "ช่วยพาไปเข้าห้องน้ำ",
    vi: "Hỗ trợ đi vệ sinh",
    id: "Bantuan ke kamar mandi",
  },
  estimatedMinutes: 30,
  prerequisiteCode: "L2-S05",
  mtcAlignment: {
    books: ["B2-L01", "B2-L05", "B2-L06", "B2-L08"],
    topics: ["assistance", "safety", "privacy"],
  },
  hookContent: {
    storyTextI18n: {
      "zh-TW":
        "劉阿嬤想上廁所,但是她走路不穩。歐寶要扶她從床邊慢慢走到廁所,提醒她「我陪您」「慢慢來」,並且尊重她的隱私。",
      th: "คุณยายหลิวอยากเข้าห้องน้ำ แต่เดินไม่มั่นคง โอบาวต้องพยุงคุณยายจากเตียงไปห้องน้ำช้า ๆ บอกว่า「ฉันอยู่ด้วย」「ค่อย ๆ ไป」 และเคารพความเป็นส่วนตัว",
      vi: "Bà Lưu muốn đi vệ sinh nhưng đi không vững. Aobao phải đỡ bà từ giường đến nhà vệ sinh từ từ, nhắc 「tôi đi cùng」「từ từ」 và tôn trọng sự riêng tư.",
      id: "Nenek Liu ingin ke kamar mandi tapi jalan tidak stabil. Aobao perlu memapahnya pelan-pelan dari tempat tidur ke kamar mandi sambil berkata 「saya menemani」「pelan-pelan」 dan menghormati privasi.",
    },
  },

  vocabularies: [
    {
      hanzi: "廁所",
      zhuyin: "ㄘㄜˋ ㄙㄨㄛˇ",
      pinyin: "cèsuǒ",
      partOfSpeech: "n.",
      translations: { th: "ห้องน้ำ", en: "toilet / restroom" },
      category: "noun",
      tags: ["essential", "eldercare"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L06" },
    },
    {
      hanzi: "馬桶",
      zhuyin: "ㄇㄚˇ ㄊㄨㄥˇ",
      pinyin: "mǎtǒng",
      partOfSpeech: "n.",
      translations: { th: "โถส้วม", en: "toilet bowl" },
      category: "eldercare",
      tags: ["essential", "eldercare"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "扶",
      zhuyin: "ㄈㄨˊ",
      pinyin: "fú",
      partOfSpeech: "v.",
      translations: { th: "พยุง", en: "to support / to hold up" },
      category: "verb",
      tags: ["essential", "eldercare", "personal-care"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "慢慢",
      zhuyin: "ㄇㄢˋ ㄇㄢˋ",
      pinyin: "mànman",
      partOfSpeech: "adv.",
      translations: { th: "ช้า ๆ", en: "slowly" },
      category: "adverb",
      tags: ["essential", "eldercare"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L01" },
    },
    {
      hanzi: "站起來",
      zhuyin: "ㄓㄢˋ ㄑㄧˇ ㄌㄞ˙",
      pinyin: "zhàn qǐlái",
      partOfSpeech: "v.",
      translations: { th: "ยืนขึ้น", en: "to stand up" },
      category: "action",
      tags: ["essential", "movement"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L08" },
    },
    {
      hanzi: "坐下",
      zhuyin: "ㄗㄨㄛˋ ㄒㄧㄚˋ",
      pinyin: "zuòxià",
      partOfSpeech: "v.",
      translations: { th: "นั่งลง", en: "to sit down" },
      category: "action",
      tags: ["essential", "movement"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L08" },
    },
    {
      hanzi: "衛生紙",
      zhuyin: "ㄨㄟˋ ㄕㄥ ㄓˇ",
      pinyin: "wèishēngzhǐ",
      partOfSpeech: "n.",
      translations: { th: "กระดาษทิชชู่", en: "toilet paper" },
      category: "eldercare",
      tags: ["essential", "eldercare"],
      difficulty: 3,
      isEldercareVocab: true,
    },
    {
      hanzi: "沖水",
      zhuyin: "ㄔㄨㄥ ㄕㄨㄟˇ",
      pinyin: "chōng shuǐ",
      partOfSpeech: "v.",
      translations: { th: "กดชักโครก", en: "to flush" },
      category: "eldercare",
      tags: ["essential", "eldercare"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "洗手",
      zhuyin: "ㄒㄧˇ ㄕㄡˇ",
      pinyin: "xǐ shǒu",
      partOfSpeech: "v.",
      translations: { th: "ล้างมือ", en: "to wash hands" },
      category: "hygiene",
      tags: ["essential", "hygiene"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L05" },
    },
    {
      hanzi: "我陪您",
      zhuyin: "ㄨㄛˇ ㄆㄟˊ ㄋㄧㄣˊ",
      pinyin: "wǒ péi nín",
      partOfSpeech: "phrase",
      translations: { th: "ฉันอยู่ด้วย", en: "I'll stay with you" },
      category: "polite",
      tags: ["essential", "eldercare", "comfort"],
      difficulty: 3,
      isEldercareVocab: true,
    },
  ],

  dialogue: [
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "劉阿嬤", th: "คุณยายหลิว" },
      hanzi: "我想上廁所。",
      pinyin: "wǒ xiǎng shàng cèsuǒ.",
      translationI18n: {
        th: "ฉันอยากเข้าห้องน้ำ",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "好,阿嬤,我扶您慢慢站起來。",
      pinyin: "hǎo, ā mà, wǒ fú nín mànman zhàn qǐlái.",
      translationI18n: {
        th: "ได้ค่ะ คุณยาย ฉันจะพยุงให้ค่อย ๆ ลุกขึ้น",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "我陪您到廁所,請慢慢走。",
      pinyin: "wǒ péi nín dào cèsuǒ, qǐng mànman zǒu.",
      translationI18n: {
        th: "ฉันอยู่กับคุณยายไปห้องน้ำ ค่อย ๆ เดินนะคะ",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "您坐下後,我先出去,需要的時候叫我。",
      pinyin: "nín zuòxià hòu, wǒ xiān chū qù, xūyào de shíhòu jiào wǒ.",
      translationI18n: {
        th: "หลังจากคุณยายนั่งแล้ว ฉันจะออกไปก่อน ต้องการให้ช่วยก็เรียกได้",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "劉阿嬤", th: "คุณยายหลิว" },
      hanzi: "好,謝謝你。我自己可以。",
      pinyin: "hǎo, xièxie nǐ. wǒ zìjǐ kěyǐ.",
      translationI18n: {
        th: "ดี ขอบคุณนะ ฉันทำเองได้",
      },
    },
  ],

  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 2,
      prompt: { symbol: "扶", hanzi: "扶", pinyin: "fú" },
      options: [
        { value: "พยุง" },
        { value: "ตี" },
        { value: "ผลัก" },
        { value: "ดึง" },
      ],
      answer: { value: "พยุง" },
      skillsTrained: ["vocab", "eldercare"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/vocab/廁所",
        instructionKey: "listenPickHanzi",
      },
      options: [
        { value: "廁所" },
        { value: "馬桶" },
        { value: "洗手" },
        { value: "衛生紙" },
      ],
      answer: { value: "廁所" },
      audioUrl: "/api/audio/vocab/廁所",
      skillsTrained: ["listening"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 2,
      prompt: { thai: "ฉันอยู่ด้วย", instructionKey: "thaiToHanzi" },
      options: [
        { value: "我陪您" },
        { value: "您好" },
        { value: "謝謝您" },
        { value: "對不起" },
      ],
      answer: { value: "我陪您" },
      explanationI18n: {
        "zh-TW": "「陪」= keep company。「我陪您」是給長輩安心感的常用句。",
        th: "「陪」 = อยู่เป็นเพื่อน「我陪您」เป็นวลีที่ใช้บ่อยเพื่อให้ผู้สูงอายุอุ่นใจ",
      },
      skillsTrained: ["vocab", "comfort"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["我", "扶", "您", "慢慢", "___"],
        sentencePinyin: "wǒ fú nín mànman ___",
        translationI18n: { th: "ฉันพยุงให้ค่อย ๆ ___ (ลุกขึ้น)" },
        instructionKey: "fillBlank",
      },
      options: [
        { value: "站起來" },
        { value: "坐下" },
        { value: "睡覺" },
        { value: "翻身" },
      ],
      answer: { value: "站起來" },
      skillsTrained: ["grammar", "movement"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["我", "陪", "您", "到", "廁所"],
        targetTranslationI18n: { th: "ฉันอยู่กับคุณไปห้องน้ำ" },
        instructionKey: "arrangeWords",
      },
      options: [
        { value: "我" },
        { value: "陪" },
        { value: "您" },
        { value: "到" },
        { value: "廁所" },
      ],
      answer: { value: ["我", "陪", "您", "到", "廁所"] },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 3,
      prompt: {
        audioUrl: "/api/audio/dialogue/L2-S06/3",
        questionI18n: {
          "zh-TW": "歐寶在阿嬤坐下後做了什麼?",
          th: "หลังคุณยายนั่งแล้ว โอบาวทำอะไร?",
        },
      },
      options: [
        { value: "出去,但需要時叫她" },
        { value: "立刻離開" },
        { value: "幫阿嬤洗手" },
        { value: "陪阿嬤聊天" },
      ],
      answer: { value: "出去,但需要時叫她" },
      audioUrl: "/api/audio/dialogue/L2-S06/3",
      skillsTrained: ["listening", "comprehension", "privacy"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 3,
      prompt: {
        hanzi: "我陪您到廁所,請慢慢走。",
        pinyin: "wǒ péi nín dào cèsuǒ, qǐng mànman zǒu.",
        audioUrl: "/api/audio/dialogue/L2-S06/2",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking", "eldercare"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 4,
      prompt: {
        targetHanzi: "陪",
        pinyin: "péi",
        translationI18n: { th: "อยู่ด้วย / เป็นเพื่อน" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "陪" },
      skillsTrained: ["writing"],
    },
  ],
};
