// L2-S02 餵藥與時間管理
//
// 場景:歐寶協助林阿嬤按時餵藥。重點是「飯前/飯後」「時間表」「別忘了」。

import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L2_S02: ScenarioDef = {
  code: "L2-S02",
  level: Level.A2_BASIC,
  orderIndex: 2,
  title: "餵藥與時間管理",
  titleI18n: {
    "zh-TW": "餵藥與時間管理",
    th: "ป้อนยาและการบริหารเวลา",
    vi: "Cho uống thuốc đúng giờ",
    id: "Pemberian obat dan manajemen waktu",
  },
  estimatedMinutes: 30,
  prerequisiteCode: "L2-S01",
  mtcAlignment: {
    books: ["B2-L06", "B2-L07", "B2-L08"],
    topics: ["meal-time", "measure-words", "polite-reminder"],
  },
  hookContent: {
    storyTextI18n: {
      "zh-TW":
        "林阿嬤每天要吃高血壓藥,飯後兩顆。今天歐寶要協助阿嬤吃藥,記得提醒她配白開水,並且小心別忘了。",
      th: "คุณยายหลินต้องทานยาความดันทุกวัน หลังอาหารสองเม็ด วันนี้โอบาวจะช่วยให้คุณยายทานยา อย่าลืมเตือนให้ดื่มน้ำเปล่าด้วย และต้องระวังอย่าลืม",
      vi: "Bà Lâm hằng ngày phải uống thuốc huyết áp, sau bữa ăn 2 viên. Hôm nay Aobao sẽ giúp bà uống thuốc, nhớ nhắc bà uống với nước ấm và cẩn thận đừng quên.",
      id: "Nenek Lin setiap hari harus minum obat tekanan darah, dua butir setelah makan. Hari ini Aobao membantu nenek minum obat, jangan lupa mengingatkan minum dengan air putih dan hati-hati jangan lupa.",
    },
  },

  vocabularies: [
    {
      hanzi: "早餐",
      zhuyin: "ㄗㄠˇ ㄘㄢ",
      pinyin: "zǎocān",
      partOfSpeech: "n.",
      translations: { th: "อาหารเช้า", en: "breakfast" },
      category: "meal",
      tags: ["essential", "meal"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L06" },
    },
    {
      hanzi: "午餐",
      zhuyin: "ㄨˇ ㄘㄢ",
      pinyin: "wǔcān",
      partOfSpeech: "n.",
      translations: { th: "อาหารกลางวัน", en: "lunch" },
      category: "meal",
      tags: ["essential", "meal"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L06" },
    },
    {
      hanzi: "晚餐",
      zhuyin: "ㄨㄢˇ ㄘㄢ",
      pinyin: "wǎncān",
      partOfSpeech: "n.",
      translations: { th: "อาหารเย็น", en: "dinner" },
      category: "meal",
      tags: ["essential", "meal"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L06" },
    },
    {
      hanzi: "飯前",
      zhuyin: "ㄈㄢˋ ㄑㄧㄢˊ",
      pinyin: "fànqián",
      partOfSpeech: "n.",
      translations: { th: "ก่อนอาหาร", en: "before meals" },
      category: "time",
      tags: ["essential", "medical"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L06" },
    },
    {
      hanzi: "飯後",
      zhuyin: "ㄈㄢˋ ㄏㄡˋ",
      pinyin: "fànhòu",
      partOfSpeech: "n.",
      translations: { th: "หลังอาหาร", en: "after meals" },
      category: "time",
      tags: ["essential", "medical"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L06" },
    },
    {
      hanzi: "兩顆",
      zhuyin: "ㄌㄧㄤˇ ㄎㄜ",
      pinyin: "liǎng kē",
      partOfSpeech: "phrase",
      translations: { th: "สองเม็ด", en: "two pills (measure word 顆)" },
      category: "quantity",
      tags: ["essential", "medical"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L07" },
    },
    {
      hanzi: "白開水",
      zhuyin: "ㄅㄞˊ ㄎㄞ ㄕㄨㄟˇ",
      pinyin: "báikāishuǐ",
      partOfSpeech: "n.",
      translations: { th: "น้ำเปล่าต้ม", en: "boiled plain water" },
      category: "eldercare",
      tags: ["essential", "eldercare", "drink"],
      difficulty: 3,
      isEldercareVocab: true,
    },
    {
      hanzi: "小心",
      zhuyin: "ㄒㄧㄠˇ ㄒㄧㄣ",
      pinyin: "xiǎoxīn",
      partOfSpeech: "v.",
      translations: { th: "ระวัง", en: "be careful" },
      category: "verb",
      tags: ["essential", "safety"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L08" },
    },
    {
      hanzi: "別忘了",
      zhuyin: "ㄅㄧㄝˊ ㄨㄤˋ ㄌㄜ˙",
      pinyin: "bié wàng le",
      partOfSpeech: "phrase",
      translations: { th: "อย่าลืม", en: "don't forget" },
      category: "phrase",
      tags: ["essential", "reminder"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L08" },
    },
    {
      hanzi: "藥",
      zhuyin: "ㄧㄠˋ",
      pinyin: "yào",
      partOfSpeech: "n.",
      translations: { th: "ยา", en: "medicine" },
      category: "medical",
      tags: ["essential", "eldercare", "medical"],
      difficulty: 1,
      isEldercareVocab: true,
    },
  ],

  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿嬤,飯後該吃藥了。",
      pinyin: "ā mà, fànhòu gāi chī yào le.",
      translationI18n: {
        th: "คุณยายคะ หลังอาหารถึงเวลาทานยาแล้วค่ะ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "林阿嬤", th: "คุณยายหลิน" },
      hanzi: "今天要吃幾顆?",
      pinyin: "jīntiān yào chī jǐ kē?",
      translationI18n: {
        th: "วันนี้ต้องทานกี่เม็ด?",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "兩顆。請配白開水,別忘了。",
      pinyin: "liǎng kē. qǐng pèi báikāishuǐ, bié wàng le.",
      translationI18n: {
        th: "สองเม็ดค่ะ กรุณาดื่มกับน้ำเปล่า อย่าลืมนะคะ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "林阿嬤", th: "คุณยายหลิน" },
      hanzi: "好,我吃了。謝謝你提醒。",
      pinyin: "hǎo, wǒ chī le. xièxie nǐ tíxǐng.",
      translationI18n: {
        th: "ดี ฉันทานแล้ว ขอบคุณที่เตือน",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "不客氣!請小心慢慢喝。",
      pinyin: "bú kèqi! qǐng xiǎoxīn mànman hē.",
      translationI18n: {
        th: "ไม่เป็นไรค่ะ ระวังด้วย ค่อย ๆ ดื่ม",
      },
    },
  ],

  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 2,
      prompt: { symbol: "飯後", hanzi: "飯後", pinyin: "fànhòu" },
      options: [
        { value: "หลังอาหาร" },
        { value: "ก่อนอาหาร" },
        { value: "ตอนเที่ยง" },
        { value: "ตอนเช้า" },
      ],
      answer: { value: "หลังอาหาร" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/vocab/藥",
        instructionKey: "listenPickHanzi",
      },
      options: [
        { value: "藥" },
        { value: "水" },
        { value: "飯" },
        { value: "茶" },
      ],
      answer: { value: "藥" },
      audioUrl: "/api/audio/vocab/藥",
      skillsTrained: ["listening", "eldercare"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 2,
      prompt: { thai: "อย่าลืม", instructionKey: "thaiToHanzi" },
      options: [
        { value: "別忘了" },
        { value: "別急" },
        { value: "別客氣" },
        { value: "別說" },
      ],
      answer: { value: "別忘了" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["飯後", "吃", "___", "藥"],
        sentencePinyin: "fànhòu chī ___ yào",
        translationI18n: { th: "ทานยา ___ เม็ดหลังอาหาร" },
        instructionKey: "fillBlank",
      },
      options: [
        { value: "兩顆" },
        { value: "兩位" },
        { value: "兩個" },
        { value: "兩本" },
      ],
      answer: { value: "兩顆" },
      explanationI18n: {
        "zh-TW": "「顆」是藥丸或圓形物的量詞,例如「一顆藥」「兩顆糖」。",
        th: "「顆」เป็นลักษณะนามสำหรับสิ่งกลม ๆ เช่น「一顆藥」「兩顆糖」",
      },
      skillsTrained: ["grammar", "measure-word"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["請", "配", "白開水", "吃藥"],
        targetTranslationI18n: { th: "กรุณาทานยากับน้ำเปล่า" },
        instructionKey: "arrangeWords",
      },
      options: [
        { value: "請" },
        { value: "配" },
        { value: "白開水" },
        { value: "吃藥" },
      ],
      answer: { value: ["請", "配", "白開水", "吃藥"] },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 3,
      prompt: {
        audioUrl: "/api/audio/dialogue/L2-S02/2",
        questionI18n: {
          "zh-TW": "歐寶說要吃幾顆藥?要配什麼水?",
          th: "โอบาวบอกให้ทานยากี่เม็ด? ดื่มกับน้ำอะไร?",
        },
      },
      options: [
        { value: "兩顆,白開水" },
        { value: "三顆,白開水" },
        { value: "兩顆,茶" },
        { value: "一顆,熱水" },
      ],
      answer: { value: "兩顆,白開水" },
      audioUrl: "/api/audio/dialogue/L2-S02/2",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 3,
      prompt: {
        hanzi: "兩顆。請配白開水,別忘了。",
        pinyin: "liǎng kē. qǐng pèi báikāishuǐ, bié wàng le.",
        audioUrl: "/api/audio/dialogue/L2-S02/2",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 4,
      prompt: {
        targetHanzi: "藥",
        pinyin: "yào",
        translationI18n: { th: "ยา" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "藥" },
      skillsTrained: ["writing"],
    },
  ],
};
