// L2-S05 量血壓與測體溫
//
// 場景:歐寶每天早上幫住民量血壓、測體溫,並回報數值。重點是讓阿公放鬆、
// 動作確實、知道怎麼描述數值高或低。

import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L2_S05: ScenarioDef = {
  code: "L2-S05",
  level: Level.A2_BASIC,
  orderIndex: 5,
  title: "量血壓與測體溫",
  titleI18n: {
    "zh-TW": "量血壓與測體溫",
    th: "วัดความดันและวัดอุณหภูมิ",
    vi: "Đo huyết áp và đo nhiệt độ",
    id: "Mengukur tekanan darah dan suhu",
  },
  estimatedMinutes: 30,
  prerequisiteCode: "L2-S04",
  mtcAlignment: {
    books: ["B2-L02", "B2-L03", "B2-L05", "B2-L11"],
    topics: ["measurement", "high-low", "result"],
  },
  hookContent: {
    storyTextI18n: {
      "zh-TW":
        "早上 7 點是量血壓時間。歐寶要幫王阿公量血壓和體溫,確認數值正常,如果太高要立刻回報護理師。",
      th: "เจ็ดโมงเช้าคือเวลาวัดความดัน โอบาวต้องวัดความดันและอุณหภูมิให้คุณตาวัง ตรวจดูว่าค่าเป็นปกติไหม ถ้าสูงเกินไปต้องรายงานพยาบาลทันที",
      vi: "Bảy giờ sáng là giờ đo huyết áp. Aobao đo huyết áp và nhiệt độ cho ông Vương, nếu quá cao phải báo y tá ngay.",
      id: "Pukul tujuh pagi adalah waktu mengukur tekanan darah. Aobao mengukur tekanan darah dan suhu Kakek Wang, jika terlalu tinggi harus segera lapor perawat.",
    },
  },

  vocabularies: [
    {
      hanzi: "血壓",
      zhuyin: "ㄒㄩㄝˋ ㄧㄚ",
      pinyin: "xuèyā",
      partOfSpeech: "n.",
      translations: { th: "ความดันโลหิต", en: "blood pressure" },
      category: "medical",
      tags: ["essential", "eldercare", "medical"],
      difficulty: 3,
      isEldercareVocab: true,
    },
    {
      hanzi: "體溫",
      zhuyin: "ㄊㄧˇ ㄨㄣ",
      pinyin: "tǐwēn",
      partOfSpeech: "n.",
      translations: { th: "อุณหภูมิร่างกาย", en: "body temperature" },
      category: "medical",
      tags: ["essential", "eldercare", "medical"],
      difficulty: 3,
      isEldercareVocab: true,
    },
    {
      hanzi: "量",
      zhuyin: "ㄌㄧㄤˊ",
      pinyin: "liáng",
      partOfSpeech: "v.",
      translations: { th: "วัด", en: "to measure" },
      category: "verb",
      tags: ["essential", "medical"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L05" },
    },
    {
      hanzi: "高",
      zhuyin: "ㄍㄠ",
      pinyin: "gāo",
      partOfSpeech: "adj.",
      translations: { th: "สูง", en: "high" },
      category: "adjective",
      tags: ["essential"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L02" },
    },
    {
      hanzi: "低",
      zhuyin: "ㄉㄧ",
      pinyin: "dī",
      partOfSpeech: "adj.",
      translations: { th: "ต่ำ", en: "low" },
      category: "adjective",
      tags: ["essential"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L02" },
    },
    {
      hanzi: "正常",
      zhuyin: "ㄓㄥˋ ㄔㄤˊ",
      pinyin: "zhèngcháng",
      partOfSpeech: "adj.",
      translations: { th: "ปกติ", en: "normal" },
      category: "adjective",
      tags: ["essential", "medical"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L05" },
    },
    {
      hanzi: "手臂",
      zhuyin: "ㄕㄡˇ ㄅㄧˋ",
      pinyin: "shǒubì",
      partOfSpeech: "n.",
      translations: { th: "แขน", en: "arm" },
      category: "body",
      tags: ["essential", "medical", "body"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "一下",
      zhuyin: "ㄧˊ ㄒㄧㄚˋ",
      pinyin: "yīxià",
      partOfSpeech: "adv.",
      translations: { th: "สักครู่ / นิดหน่อย", en: "for a moment" },
      category: "adverb",
      tags: ["essential"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L03" },
    },
    {
      hanzi: "不會痛",
      zhuyin: "ㄅㄨˊ ㄏㄨㄟˋ ㄊㄨㄥˋ",
      pinyin: "bùhuì tòng",
      partOfSpeech: "phrase",
      translations: { th: "ไม่เจ็บ", en: "won't hurt" },
      category: "phrase",
      tags: ["essential", "eldercare", "comfort"],
      difficulty: 3,
      isEldercareVocab: true,
    },
    {
      hanzi: "結果",
      zhuyin: "ㄐㄧㄝˊ ㄍㄨㄛˇ",
      pinyin: "jiéguǒ",
      partOfSpeech: "n.",
      translations: { th: "ผลลัพธ์", en: "result" },
      category: "noun",
      tags: ["essential"],
      difficulty: 3,
      mtcReference: { book: "B2", lesson: "L11" },
    },
  ],

  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿公,早安!我幫您量血壓。",
      pinyin: "ā gōng, zǎo'ān! wǒ bāng nín liáng xuèyā.",
      translationI18n: {
        th: "คุณตา อรุณสวัสดิ์ค่ะ! ฉันจะวัดความดันให้นะคะ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿公", th: "คุณตาหวัง" },
      hanzi: "好,要用哪一隻手?",
      pinyin: "hǎo, yào yòng nǎ yī zhī shǒu?",
      translationI18n: {
        th: "ดี ใช้แขนข้างไหน?",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "請伸出左手臂,放輕鬆,不會痛。",
      pinyin: "qǐng shēn chū zuǒ shǒubì, fàng qīngsōng, bùhuì tòng.",
      translationI18n: {
        th: "ขอแขนซ้ายค่ะ ผ่อนคลายนะ ไม่เจ็บค่ะ",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "好,結果出來了:血壓正常,體溫也正常。",
      pinyin: "hǎo, jiéguǒ chū lái le: xuèyā zhèngcháng, tǐwēn yě zhèngcháng.",
      translationI18n: {
        th: "ได้แล้วค่ะ ผลออกมา: ความดันปกติ อุณหภูมิก็ปกติ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿公", th: "คุณตาหวัง" },
      hanzi: "太好了,謝謝你。",
      pinyin: "tài hǎo le, xièxie nǐ.",
      translationI18n: {
        th: "ดีมากเลย ขอบคุณนะ",
      },
    },
  ],

  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 2,
      prompt: { symbol: "血壓", hanzi: "血壓", pinyin: "xuèyā" },
      options: [
        { value: "ความดันโลหิต" },
        { value: "อุณหภูมิ" },
        { value: "ชีพจร" },
        { value: "น้ำหนัก" },
      ],
      answer: { value: "ความดันโลหิต" },
      skillsTrained: ["vocab", "medical"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/vocab/體溫",
        instructionKey: "listenPickHanzi",
      },
      options: [
        { value: "體溫" },
        { value: "血壓" },
        { value: "結果" },
        { value: "正常" },
      ],
      answer: { value: "體溫" },
      audioUrl: "/api/audio/vocab/體溫",
      skillsTrained: ["listening", "medical"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 2,
      prompt: { thai: "ปกติ", instructionKey: "thaiToHanzi" },
      options: [
        { value: "正常" },
        { value: "高" },
        { value: "低" },
        { value: "好" },
      ],
      answer: { value: "正常" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["請", "伸出", "___", "手臂"],
        sentencePinyin: "qǐng shēn chū ___ shǒubì",
        translationI18n: { th: "กรุณายืนแขน ___ ออกมา" },
        instructionKey: "fillBlank",
      },
      options: [
        { value: "左" },
        { value: "好" },
        { value: "高" },
        { value: "您" },
      ],
      answer: { value: "左" },
      explanationI18n: {
        "zh-TW": "量血壓通常用左手臂,因為靠近心臟。",
        th: "การวัดความดันมักใช้แขนซ้ายเพราะอยู่ใกล้หัวใจ",
      },
      skillsTrained: ["grammar", "medical"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["血壓", "正常", ",", "體溫", "也", "正常"],
        targetTranslationI18n: { th: "ความดันปกติ อุณหภูมิก็ปกติ" },
        instructionKey: "arrangeWords",
      },
      options: [
        { value: "血壓" },
        { value: "正常" },
        { value: "," },
        { value: "體溫" },
        { value: "也" },
        { value: "正常" },
      ],
      answer: { value: ["血壓", "正常", ",", "體溫", "也", "正常"] },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 3,
      prompt: {
        audioUrl: "/api/audio/dialogue/L2-S05/3",
        questionI18n: {
          "zh-TW": "歐寶量出來的結果是什麼?",
          th: "ผลที่โอบาววัดได้คืออะไร?",
        },
      },
      options: [
        { value: "都正常" },
        { value: "血壓太高" },
        { value: "體溫太低" },
        { value: "都太低" },
      ],
      answer: { value: "都正常" },
      audioUrl: "/api/audio/dialogue/L2-S05/3",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 3,
      prompt: {
        hanzi: "請伸出左手臂,放輕鬆,不會痛。",
        pinyin: "qǐng shēn chū zuǒ shǒubì, fàng qīngsōng, bùhuì tòng.",
        audioUrl: "/api/audio/dialogue/L2-S05/2",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking", "eldercare"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 4,
      prompt: {
        targetHanzi: "量",
        pinyin: "liáng",
        translationI18n: { th: "วัด" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "量" },
      skillsTrained: ["writing"],
    },
  ],
};
