// L2-S01 餵食協助(軟食)
//
// 場景:歐寶餵王阿公吃午餐。重點是「慢慢來」「別急」「噎到」的安全意識。

import { ExerciseType, Level } from "@prisma/client";
import type { ScenarioDef } from "./_types";

export const L2_S01: ScenarioDef = {
  code: "L2-S01",
  level: Level.A2_BASIC,
  orderIndex: 1,
  title: "餵食協助(軟食)",
  titleI18n: {
    "zh-TW": "餵食協助(軟食)",
    th: "ช่วยเหลือป้อนอาหาร (อาหารอ่อน)",
    vi: "Hỗ trợ bón ăn (đồ mềm)",
    id: "Bantuan menyuapi (makanan lunak)",
  },
  estimatedMinutes: 30,
  mtcAlignment: {
    books: ["B2-L01", "B2-L02", "B2-L03", "B2-L05"],
    topics: ["food", "verb-reduplication", "negative-imperative"],
  },
  hookContent: {
    storyTextI18n: {
      "zh-TW":
        "中午十二點,該餵王阿公吃午餐了。今天是軟食(粥+蒸蛋)。歐寶要鼓勵阿公多吃,但要慢慢來,小心噎到。",
      th: "เที่ยงสิบสองนาฬิกา ถึงเวลาป้อนอาหารกลางวันให้คุณตาวัง วันนี้เป็นอาหารอ่อน (โจ๊ก+ไข่ตุ๋น) โอบาวต้องให้กำลังใจคุณตาทานเยอะ ๆ แต่ค่อย ๆ ระวังสำลัก",
      vi: "Mười hai giờ trưa, đến giờ bón cơm trưa cho ông Vương. Hôm nay là đồ ăn mềm (cháo + trứng hấp). Aobao cần khích lệ ông ăn nhiều nhưng phải từ từ, cẩn thận sặc.",
      id: "Pukul dua belas siang, waktunya menyuapi makan siang Kakek Wang. Hari ini makanan lunak (bubur + telur kukus). Aobao perlu memberi semangat agar kakek makan banyak, tapi pelan-pelan, hati-hati tersedak.",
    },
  },

  vocabularies: [
    {
      hanzi: "慢慢",
      zhuyin: "ㄇㄢˋ ㄇㄢˋ",
      pinyin: "mànman",
      partOfSpeech: "adv.",
      translations: { th: "ช้า ๆ / ค่อย ๆ", en: "slowly" },
      category: "adverb",
      tags: ["essential", "eldercare", "safety"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L01" },
    },
    {
      hanzi: "嚼",
      zhuyin: "ㄐㄧㄠˊ",
      pinyin: "jiáo",
      partOfSpeech: "v.",
      translations: { th: "เคี้ยว", en: "to chew" },
      category: "verb",
      tags: ["essential", "eldercare", "feeding"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L02" },
    },
    {
      hanzi: "吞",
      zhuyin: "ㄊㄨㄣ",
      pinyin: "tūn",
      partOfSpeech: "v.",
      translations: { th: "กลืน", en: "to swallow" },
      category: "verb",
      tags: ["essential", "eldercare", "feeding"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L02" },
    },
    {
      hanzi: "別",
      zhuyin: "ㄅㄧㄝˊ",
      pinyin: "bié",
      partOfSpeech: "adv.",
      translations: { th: "อย่า", en: "don't (negative imperative)" },
      category: "adverb",
      tags: ["essential", "grammar"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L03" },
    },
    {
      hanzi: "急",
      zhuyin: "ㄐㄧˊ",
      pinyin: "jí",
      partOfSpeech: "adj.",
      translations: { th: "รีบ / ใจร้อน", en: "anxious / hurry" },
      category: "adjective",
      tags: ["essential", "emotion"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L03" },
    },
    {
      hanzi: "試試看",
      zhuyin: "ㄕˋ ㄕˋ ㄎㄢˋ",
      pinyin: "shìshìkàn",
      partOfSpeech: "phrase",
      translations: { th: "ลองดูสิ", en: "give it a try" },
      category: "phrase",
      tags: ["essential", "encouragement"],
      difficulty: 3,
      mtcReference: { book: "B2", lesson: "L05" },
    },
    {
      hanzi: "喜歡",
      zhuyin: "ㄒㄧˇ ㄏㄨㄢ",
      pinyin: "xǐhuan",
      partOfSpeech: "v.",
      translations: { th: "ชอบ", en: "to like" },
      category: "verb",
      tags: ["essential", "emotion"],
      difficulty: 1,
      mtcReference: { book: "B2", lesson: "L01" },
    },
    {
      hanzi: "食物",
      zhuyin: "ㄕˊ ㄨˋ",
      pinyin: "shíwù",
      partOfSpeech: "n.",
      translations: { th: "อาหาร", en: "food" },
      category: "noun",
      tags: ["essential", "feeding"],
      difficulty: 2,
      mtcReference: { book: "B2", lesson: "L02" },
    },
    {
      hanzi: "餵",
      zhuyin: "ㄨㄟˋ",
      pinyin: "wèi",
      partOfSpeech: "v.",
      translations: { th: "ป้อน", en: "to feed" },
      category: "eldercare",
      tags: ["essential", "eldercare", "feeding"],
      difficulty: 2,
      isEldercareVocab: true,
    },
    {
      hanzi: "噎到",
      zhuyin: "ㄧㄝ ㄉㄠˋ",
      pinyin: "yē dào",
      partOfSpeech: "v.",
      translations: { th: "สำลัก / ติดคอ", en: "to choke" },
      category: "eldercare",
      tags: ["essential", "eldercare", "safety"],
      difficulty: 3,
      isEldercareVocab: true,
    },
  ],

  dialogue: [
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "阿公,該吃午餐了,我餵您。",
      pinyin: "ā gōng, gāi chī wǔcān le, wǒ wèi nín.",
      translationI18n: {
        th: "คุณตา ถึงเวลาทานข้าวเที่ยงแล้วค่ะ ฉันจะป้อนให้นะคะ",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿公", th: "คุณตาหวัง" },
      hanzi: "今天的食物是什麼?",
      pinyin: "jīntiān de shíwù shì shénme?",
      translationI18n: {
        th: "อาหารวันนี้มีอะไรบ้าง?",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "今天有粥跟蒸蛋,您試試看。",
      pinyin: "jīntiān yǒu zhōu gēn zhēngdàn, nín shìshìkàn.",
      translationI18n: {
        th: "วันนี้มีโจ๊กกับไข่ตุ๋น ลองชิมดูสิคะ",
      },
    },
    {
      speaker: "learner",
      speakerLabel: { "zh-TW": "歐寶", th: "โอบาว" },
      hanzi: "別急,慢慢嚼,小心噎到。",
      pinyin: "bié jí, mànman jiáo, xiǎoxīn yē dào.",
      translationI18n: {
        th: "อย่ารีบ ค่อย ๆ เคี้ยว ระวังสำลักด้วย",
      },
    },
    {
      speaker: "elder",
      speakerLabel: { "zh-TW": "王阿公", th: "คุณตาหวัง" },
      hanzi: "好,我喜歡這個粥。",
      pinyin: "hǎo, wǒ xǐhuan zhège zhōu.",
      translationI18n: {
        th: "ดี ฉันชอบโจ๊กนี้",
      },
    },
  ],

  exercises: [
    {
      type: ExerciseType.VOCAB_MCQ,
      difficulty: 2,
      prompt: { symbol: "餵", hanzi: "餵", pinyin: "wèi" },
      options: [
        { value: "ป้อน" },
        { value: "เคี้ยว" },
        { value: "กลืน" },
        { value: "ดื่ม" },
      ],
      answer: { value: "ป้อน" },
      skillsTrained: ["vocab", "eldercare"],
    },
    {
      type: ExerciseType.VOCAB_LISTEN_CHOOSE,
      difficulty: 2,
      prompt: {
        audioUrl: "/api/audio/vocab/噎到",
        instructionKey: "listenPickHanzi",
      },
      options: [
        { value: "噎到" },
        { value: "嚼" },
        { value: "吞" },
        { value: "餵" },
      ],
      answer: { value: "噎到" },
      audioUrl: "/api/audio/vocab/噎到",
      skillsTrained: ["listening", "eldercare"],
    },
    {
      type: ExerciseType.VOCAB_MCQ_REVERSE,
      difficulty: 2,
      prompt: { thai: "ลองดูสิ", instructionKey: "thaiToHanzi" },
      options: [
        { value: "試試看" },
        { value: "再說" },
        { value: "怎麼樣" },
        { value: "請坐" },
      ],
      answer: { value: "試試看" },
      skillsTrained: ["vocab"],
    },
    {
      type: ExerciseType.GRAMMAR_FILL,
      difficulty: 2,
      prompt: {
        sentenceParts: ["___", "急", ",", "慢慢", "嚼"],
        sentencePinyin: "___ jí, mànman jiáo",
        translationI18n: { th: "อย่ารีบ ค่อย ๆ เคี้ยว" },
        instructionKey: "fillBlank",
      },
      options: [
        { value: "別" },
        { value: "您" },
        { value: "我" },
        { value: "好" },
      ],
      answer: { value: "別" },
      explanationI18n: {
        "zh-TW": "「別 + 動詞/形容詞」表示禁止或勸阻,「別急」= 不要急。",
        th: "「別 + V/Adj」ใช้ห้ามหรือบอกอย่าทำ「別急」= อย่ารีบ",
      },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.GRAMMAR_ARRANGE,
      difficulty: 3,
      prompt: {
        words: ["阿公", ",", "我", "餵", "您"],
        targetTranslationI18n: { th: "คุณตาคะ ฉันจะป้อนคุณตา" },
        instructionKey: "arrangeWords",
      },
      options: [
        { value: "阿公" },
        { value: "," },
        { value: "我" },
        { value: "餵" },
        { value: "您" },
      ],
      answer: { value: ["阿公", ",", "我", "餵", "您"] },
      skillsTrained: ["grammar"],
    },
    {
      type: ExerciseType.LISTEN_DIALOGUE_MCQ,
      difficulty: 3,
      prompt: {
        audioUrl: "/api/audio/dialogue/L2-S01/2",
        questionI18n: {
          "zh-TW": "今天的食物有什麼?",
          th: "อาหารวันนี้มีอะไรบ้าง?",
        },
      },
      options: [
        { value: "粥跟蒸蛋" },
        { value: "麵跟湯" },
        { value: "白飯跟魚" },
        { value: "麵包跟牛奶" },
      ],
      answer: { value: "粥跟蒸蛋" },
      audioUrl: "/api/audio/dialogue/L2-S01/2",
      skillsTrained: ["listening", "comprehension"],
    },
    {
      type: ExerciseType.SPEAK_REPEAT,
      difficulty: 3,
      prompt: {
        hanzi: "別急,慢慢嚼,小心噎到。",
        pinyin: "bié jí, mànman jiáo, xiǎoxīn yē dào.",
        audioUrl: "/api/audio/dialogue/L2-S01/3",
        instructionKey: "speakRepeat",
        notSupported: true,
      },
      options: [],
      answer: { value: "ok" },
      skillsTrained: ["speaking", "eldercare"],
    },
    {
      type: ExerciseType.WRITE_HANZI,
      difficulty: 4,
      prompt: {
        targetHanzi: "餵",
        pinyin: "wèi",
        translationI18n: { th: "ป้อน" },
        instructionKey: "writeHanzi",
        notSupported: true,
      },
      options: [],
      answer: { value: "餵" },
      skillsTrained: ["writing"],
    },
  ],
};
