/**
 * Seed AAY financial-statement vocabulary from
 * 「財務報表詞彙對照表 ตารางคำศัพท์งบการเงิน.xlsx」.
 *
 * 207 entries across 14 sub-categories prefixed `finance-*`.
 * Each entry carries en / th / vi / id translations so cards render
 * properly in every locale.
 *
 * Categories registered for the /mywork landing:
 *   finance-institution          🏢 institutions & units (7)
 *   finance-report-type          📊 report types (6)
 *   finance-period-header        📅 period & headers (8)
 *   finance-income               💰 income items (24)
 *   finance-expense-personnel    💸 personnel expenses (14)
 *   finance-expense-office       🏥 office & maintenance (23)
 *   finance-expense-insurance    🛡️ insurance & other (6)
 *   finance-expense-operations   🍱 operations & materials (14)
 *   finance-admin-allocation     📋 administrative & allocation (6)
 *   finance-profitloss           📈 profit & loss (11)
 *   finance-depreciation         🏠 depreciation sheet fields (28)
 *   finance-measure              🔢 measure words & time (9)
 *   finance-equipment            🛏️ equipment & assets (33)
 *   finance-misc                 📝 subsidies & business common (18)
 */
import * as fs from "fs";
import * as path from "path";
import { PrismaClient, Level } from "@prisma/client";

const envFile = path.resolve(process.cwd(), ".env.local");
if (fs.existsSync(envFile)) {
  fs.readFileSync(envFile, "utf-8").split("\n").forEach((line) => {
    const m = line.match(/^([^#=]+)=(.*)/);
    if (m) process.env[m[1].trim()] = m[2].trim().replace(/^['"]|['"]$/g, "");
  });
}

const db = new PrismaClient();

interface Row {
  hanzi: string;
  pinyin: string;
  category: string;
  partOfSpeech?: string;
  tr: { en: string; th: string; vi: string; id: string };
  note?: string;
}

const ROWS: Row[] = [
  // 🏢 機構與單位 / Institutions & Units (7)
  { hanzi: "財團法人",         pinyin: "cáituán fǎrén",          category: "finance-institution", partOfSpeech: "N", tr: { en: "incorporated foundation",                  th: "มูลนิธิ (นิติบุคคล)",                              vi: "Pháp nhân quỹ",                              id: "Yayasan berbadan hukum" } },
  { hanzi: "臺北市私立愛愛院", pinyin: "Táiběi shì sīlì Àiʼài yuàn", category: "finance-institution", partOfSpeech: "N", tr: { en: "Taipei AAY Private Eldercare Home",       th: "บ้านพักคนชราเอกชนอ้ายอ้าย เมืองไทเป",            vi: "Nhà dưỡng lão tư nhân AAY Đài Bắc",          id: "Panti Wreda Swasta AAY Taipei" } },
  { hanzi: "院本部",           pinyin: "yuàn běnbù",            category: "finance-institution", partOfSpeech: "N", tr: { en: "main facility / headquarters",            th: "สำนักงานใหญ่",                                  vi: "Trụ sở chính",                                id: "Kantor pusat / Cabang utama" } },
  { hanzi: "東明",             pinyin: "Dōngmíng",              category: "finance-institution", partOfSpeech: "Name", tr: { en: "Dongming branch (Nangang district)",   th: "สาขาตงหมิง",                                    vi: "Chi nhánh Đông Minh",                          id: "Cabang Dongming" } },
  { hanzi: "愛力勇",           pinyin: "Àilìyǒng",              category: "finance-institution", partOfSpeech: "Name", tr: { en: "AiLiYong (day-care branch)",            th: "อ้ายลี่หย่ง (ศูนย์ดูแลกลางวัน)",                  vi: "AiLiYong (trung tâm Day care)",               id: "AiLiYong (cabang Day Care)" } },
  { hanzi: "A單位",            pinyin: "A dānwèi",              category: "finance-institution", partOfSpeech: "N", tr: { en: "Unit A (in-home care unit)",              th: "หน่วย A (บริการดูแลที่บ้าน)",                    vi: "Đơn vị A (chăm sóc tại nhà)",                  id: "Unit A (perawatan di rumah)" } },
  { hanzi: "日照中心",         pinyin: "rìzhào zhōngxīn",       category: "finance-institution", partOfSpeech: "N", tr: { en: "day-care center",                          th: "ศูนย์ดูแลกลางวัน (Day Care)",                    vi: "Trung tâm chăm sóc ban ngày",                  id: "Pusat Day Care" } },

  // 📊 報表類型 / Report Types (6)
  { hanzi: "收支表",           pinyin: "shōuzhī biǎo",          category: "finance-report-type", partOfSpeech: "N", tr: { en: "income & expenditure statement",         th: "งบรายรับรายจ่าย",                                vi: "Báo cáo thu chi",                                id: "Laporan pemasukan dan pengeluaran" } },
  { hanzi: "收支餘絀表",       pinyin: "shōuzhī yúchù biǎo",    category: "finance-report-type", partOfSpeech: "N", tr: { en: "statement of surplus/deficit (NPO)",     th: "งบกำไรขาดทุน (สำหรับ NGO)",                       vi: "Báo cáo dư - thiếu (NGO)",                       id: "Laporan surplus/defisit (NPO)" } },
  { hanzi: "全年度收支餘絀表", pinyin: "quán niándù shōuzhī yúchù biǎo", category: "finance-report-type", partOfSpeech: "N", tr: { en: "annual income & surplus/deficit statement", th: "งบรายรับรายจ่ายและกำไรขาดทุนประจำปี",         vi: "Báo cáo thu chi & dư-thiếu cả năm",              id: "Laporan tahunan pendapatan & surplus/defisit" } },
  { hanzi: "合併",             pinyin: "hébìng",                category: "finance-report-type", partOfSpeech: "N", tr: { en: "consolidated / combined",                 th: "รวม / Combined",                                  vi: "Hợp nhất",                                       id: "Konsolidasi / Gabungan" } },
  { hanzi: "初版",             pinyin: "chūbǎn",                category: "finance-report-type", partOfSpeech: "N", tr: { en: "first draft / initial version",          th: "ฉบับร่างแรก / Draft",                              vi: "Bản nháp đầu",                                   id: "Versi awal / Draft" } },
  { hanzi: "單位:元",          pinyin: "dānwèi: yuán",          category: "finance-report-type", partOfSpeech: "N", tr: { en: "unit: TWD (NT$)",                          th: "หน่วย: ดอลลาร์ไต้หวัน (TWD)",                       vi: "Đơn vị: đô la Đài Loan (TWD)",                   id: "Satuan: Dolar Taiwan (TWD)" } },

  // 📅 期別與表頭 / Period & Headers (8)
  { hanzi: "科目編號",         pinyin: "kēmù biānhào",          category: "finance-period-header", partOfSpeech: "N", tr: { en: "account code",                              th: "รหัสบัญชี",                                       vi: "Mã tài khoản",                                   id: "Kode akun" } },
  { hanzi: "項目",             pinyin: "xiàngmù",               category: "finance-period-header", partOfSpeech: "N", tr: { en: "item / line item",                          th: "รายการ",                                          vi: "Khoản mục",                                       id: "Item / Pos" } },
  { hanzi: "01期",             pinyin: "líng yī qí",            category: "finance-period-header", partOfSpeech: "N", tr: { en: "Period 1 (January)",                       th: "งวดที่ 1 (มกราคม)",                                 vi: "Kỳ 1 (tháng 1)",                                  id: "Periode 1 (Januari)" } },
  { hanzi: "02期",             pinyin: "líng èr qí",            category: "finance-period-header", partOfSpeech: "N", tr: { en: "Period 2 (February)",                      th: "งวดที่ 2 (กุมภาพันธ์)",                              vi: "Kỳ 2 (tháng 2)",                                  id: "Periode 2 (Februari)" } },
  { hanzi: "03期",             pinyin: "líng sān qí",           category: "finance-period-header", partOfSpeech: "N", tr: { en: "Period 3 (March)",                         th: "งวดที่ 3 (มีนาคม)",                                  vi: "Kỳ 3 (tháng 3)",                                  id: "Periode 3 (Maret)" } },
  { hanzi: "合計",             pinyin: "héjì",                  category: "finance-period-header", partOfSpeech: "N", tr: { en: "total",                                      th: "รวม / Total",                                      vi: "Tổng cộng",                                       id: "Total / Jumlah" } },
  { hanzi: "小計",             pinyin: "xiǎojì",                category: "finance-period-header", partOfSpeech: "N", tr: { en: "subtotal",                                  th: "รวมย่อย / Subtotal",                               vi: "Tổng phụ",                                        id: "Subtotal" } },
  { hanzi: "總額",             pinyin: "zǒngʼé",                category: "finance-period-header", partOfSpeech: "N", tr: { en: "grand total",                              th: "ยอดรวมทั้งหมด",                                    vi: "Tổng số",                                         id: "Total keseluruhan" } },

  // 💰 收入科目 / Income Items (24)
  { hanzi: "收入",             pinyin: "shōurù",                category: "finance-income", partOfSpeech: "N", tr: { en: "income / revenue",                          th: "รายรับ",                                          vi: "Thu nhập",                                       id: "Pendapatan" } },
  { hanzi: "收入合計",         pinyin: "shōurù héjì",           category: "finance-income", partOfSpeech: "N", tr: { en: "total income",                              th: "รวมรายรับ",                                       vi: "Tổng thu nhập",                                   id: "Total Pendapatan" } },
  { hanzi: "政府補助款",       pinyin: "zhèngfǔ bǔzhù kuǎn",    category: "finance-income", partOfSpeech: "N", tr: { en: "government subsidy",                        th: "เงินอุดหนุนจากรัฐบาล",                              vi: "Trợ cấp chính phủ",                              id: "Subsidi pemerintah" } },
  { hanzi: "社會局補助款",     pinyin: "shèhuì jú bǔzhù kuǎn",  category: "finance-income", partOfSpeech: "N", tr: { en: "Social Welfare Bureau subsidy",            th: "เงินอุดหนุนจากกรมสวัสดิการสังคม",                   vi: "Trợ cấp Sở Phúc lợi xã hội",                     id: "Subsidi Dinas Sosial" } },
  { hanzi: "衛福部補助款",     pinyin: "wèi fú bù bǔzhù kuǎn",  category: "finance-income", partOfSpeech: "N", tr: { en: "Ministry of Health subsidy",                th: "เงินอุดหนุนจากกระทรวงสาธารณสุข",                    vi: "Trợ cấp Bộ Y tế",                                 id: "Subsidi Kemenkes" } },
  { hanzi: "加菜金補助",       pinyin: "jiācài jīn bǔzhù",      category: "finance-income", partOfSpeech: "N", tr: { en: "extra meal-fund subsidy",                   th: "เงินอุดหนุนค่าอาหารเพิ่มเติม",                       vi: "Trợ cấp chi phí ăn uống bổ sung",                id: "Subsidi tambahan biaya makan" } },
  { hanzi: "特別處遇費",       pinyin: "tèbié chǔyù fèi",       category: "finance-income", partOfSpeech: "N", tr: { en: "special-care fee",                            th: "ค่าดูแลพิเศษ",                                     vi: "Phí chăm sóc đặc biệt",                          id: "Biaya perawatan khusus" } },
  { hanzi: "專業服務人員補助", pinyin: "zhuānyè fúwù rényuán bǔzhù", category: "finance-income", partOfSpeech: "N", tr: { en: "professional-staff subsidy",        th: "เงินอุดหนุนบุคลากรวิชาชีพ",                          vi: "Trợ cấp nhân viên chuyên nghiệp",                id: "Subsidi tenaga profesional" } },
  { hanzi: "其他補助收入",     pinyin: "qítā bǔzhù shōurù",     category: "finance-income", partOfSpeech: "N", tr: { en: "other subsidy income",                      th: "รายรับเงินอุดหนุนอื่นๆ",                            vi: "Thu nhập trợ cấp khác",                          id: "Pendapatan subsidi lainnya" } },
  { hanzi: "捐款收入",         pinyin: "juānkuǎn shōurù",       category: "finance-income", partOfSpeech: "N", tr: { en: "donation income",                            th: "รายรับเงินบริจาค",                                  vi: "Thu nhập từ quyên góp",                          id: "Pendapatan donasi" } },
  { hanzi: "一般捐款",         pinyin: "yībān juānkuǎn",        category: "finance-income", partOfSpeech: "N", tr: { en: "general donations",                         th: "เงินบริจาคทั่วไป",                                  vi: "Quyên góp thông thường",                         id: "Donasi umum" } },
  { hanzi: "勸募捐款",         pinyin: "quànmù juānkuǎn",       category: "finance-income", partOfSpeech: "N", tr: { en: "fund-raising donations",                    th: "เงินบริจาคจากการระดมทุน",                            vi: "Quyên góp từ vận động",                          id: "Donasi penggalangan dana" } },
  { hanzi: "實物捐贈",         pinyin: "shíwù juānzèng",        category: "finance-income", partOfSpeech: "N", tr: { en: "in-kind donations",                          th: "การบริจาคในรูปสิ่งของ",                              vi: "Quyên góp hiện vật",                             id: "Donasi barang" } },
  { hanzi: "安養護收入",       pinyin: "ān yǎnghù shōurù",      category: "finance-income", partOfSpeech: "N", tr: { en: "eldercare service income (main)",          th: "รายรับค่าดูแลผู้สูงอายุ",                            vi: "Thu nhập từ dịch vụ chăm sóc",                   id: "Pendapatan layanan perawatan lansia" } },
  { hanzi: "安養護月費收入",   pinyin: "ān yǎnghù yuè fèi shōurù", category: "finance-income", partOfSpeech: "N", tr: { en: "monthly fee income",                    th: "รายรับค่าธรรมเนียมรายเดือน",                          vi: "Thu nhập phí hàng tháng",                        id: "Pendapatan iuran bulanan" } },
  { hanzi: "安養護耗材收入",   pinyin: "ān yǎnghù hàocái shōurù", category: "finance-income", partOfSpeech: "N", tr: { en: "consumable supplies income",            th: "รายรับค่าวัสดุสิ้นเปลือง",                            vi: "Thu nhập vật tư tiêu hao",                       id: "Pendapatan bahan habis pakai" } },
  { hanzi: "愛心扶助",         pinyin: "àixīn fúzhù",           category: "finance-income", partOfSpeech: "N", tr: { en: "charity discount",                            th: "เงินสงเคราะห์เมตตา",                                vi: "Trợ giúp từ thiện",                              id: "Bantuan amal" } },
  { hanzi: "日照收入",         pinyin: "rìzhào shōurù",         category: "finance-income", partOfSpeech: "N", tr: { en: "day-care income",                             th: "รายรับศูนย์ดูแลกลางวัน",                              vi: "Thu nhập trung tâm Day care",                    id: "Pendapatan Day Care" } },
  { hanzi: "日照服務收入",     pinyin: "rìzhào fúwù shōurù",    category: "finance-income", partOfSpeech: "N", tr: { en: "day-care service income",                    th: "รายรับค่าบริการดูแลกลางวัน",                          vi: "Thu nhập dịch vụ Day care",                      id: "Pendapatan jasa Day Care" } },
  { hanzi: "A單位服務收入",    pinyin: "A dānwèi fúwù shōurù",  category: "finance-income", partOfSpeech: "N", tr: { en: "Unit A service income",                       th: "รายรับค่าบริการหน่วย A",                              vi: "Thu nhập dịch vụ Đơn vị A",                      id: "Pendapatan layanan Unit A" } },
  { hanzi: "利息收入",         pinyin: "lìxí shōurù",           category: "finance-income", partOfSpeech: "N", tr: { en: "interest income",                              th: "รายรับดอกเบี้ย",                                    vi: "Thu nhập lãi",                                    id: "Pendapatan bunga" } },
  { hanzi: "其他收入",         pinyin: "qítā shōurù",           category: "finance-income", partOfSpeech: "N", tr: { en: "other income",                                 th: "รายรับอื่นๆ",                                       vi: "Thu nhập khác",                                  id: "Pendapatan lainnya" } },
  { hanzi: "其他雜項收入",     pinyin: "qítā záxiàng shōurù",   category: "finance-income", partOfSpeech: "N", tr: { en: "miscellaneous income",                         th: "รายรับเบ็ดเตล็ดอื่นๆ",                              vi: "Thu nhập linh tinh",                              id: "Pendapatan lain-lain" } },
  { hanzi: "優免",             pinyin: "yōumiǎn",               category: "finance-income", partOfSpeech: "N", tr: { en: "discount / waiver",                            th: "ส่วนลด/ยกเว้น",                                     vi: "Giảm giá / Miễn",                                id: "Potongan / Pembebasan" } },

  // 💸 支出科目 - 人事費 / Personnel Expenses (14)
  { hanzi: "支出",             pinyin: "zhīchū",                category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "expense",                              th: "รายจ่าย",                                          vi: "Chi phí",                                         id: "Pengeluaran" } },
  { hanzi: "支出總額",         pinyin: "zhīchū zǒngʼé",         category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "total expenses",                       th: "รวมรายจ่ายทั้งหมด",                                  vi: "Tổng chi phí",                                    id: "Total Pengeluaran" } },
  { hanzi: "人事費",           pinyin: "rénshì fèi",            category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "personnel expenses",                   th: "ค่าใช้จ่ายบุคลากร",                                  vi: "Chi phí nhân sự",                                 id: "Biaya personel" } },
  { hanzi: "人事費-1",          pinyin: "rénshì fèi - 1",        category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "personnel expenses-1 (admin)",        th: "ค่าใช้จ่ายบุคลากร-1 (ฝ่ายบริหาร)",                    vi: "Chi phí nhân sự-1 (Hành chính)",                  id: "Biaya personel-1 (administrasi)" } },
  { hanzi: "人事費-2",          pinyin: "rénshì fèi - 2",        category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "personnel expenses-2 (operations)", th: "ค่าใช้จ่ายบุคลากร-2 (ฝ่ายปฏิบัติงาน)",                vi: "Chi phí nhân sự-2 (Vận hành)",                    id: "Biaya personel-2 (operasional)" } },
  { hanzi: "薪資",             pinyin: "xīnzī",                 category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "salary",                                th: "เงินเดือน",                                         vi: "Lương",                                           id: "Gaji" } },
  { hanzi: "薪資支出-應稅",    pinyin: "xīnzī zhīchū - yìng shuì", category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "salary expense (taxable)",         th: "เงินเดือน - เสียภาษี",                              vi: "Chi lương (chịu thuế)",                           id: "Pengeluaran gaji (kena pajak)" } },
  { hanzi: "薪資支出-免稅",    pinyin: "xīnzī zhīchū - miǎn shuì", category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "salary expense (tax-exempt)",     th: "เงินเดือน - ยกเว้นภาษี",                            vi: "Chi lương (miễn thuế)",                           id: "Pengeluaran gaji (bebas pajak)" } },
  { hanzi: "伙食津貼",         pinyin: "huǒshí jīntiē",         category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "meal allowance",                       th: "เบี้ยเลี้ยงค่าอาหาร",                               vi: "Phụ cấp ăn uống",                                id: "Tunjangan makan" } },
  { hanzi: "加班費",           pinyin: "jiābān fèi",            category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "overtime pay",                         th: "ค่าล่วงเวลา (OT)",                                 vi: "Tiền tăng ca",                                   id: "Upah lembur (OT)" } },
  { hanzi: "加班費-免稅",      pinyin: "jiābān fèi - miǎn shuì", category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "overtime pay (tax-exempt)",        th: "ค่าล่วงเวลา - ยกเว้นภาษี",                          vi: "Tiền tăng ca (miễn thuế)",                       id: "Upah lembur (bebas pajak)" } },
  { hanzi: "職工福利",         pinyin: "zhígōng fúlì",          category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "employee welfare",                     th: "สวัสดิการพนักงาน",                                  vi: "Phúc lợi nhân viên",                             id: "Kesejahteraan karyawan" } },
  { hanzi: "訓練費",           pinyin: "xùnliàn fèi",           category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "training expenses",                    th: "ค่าอบรม",                                          vi: "Phí đào tạo",                                    id: "Biaya pelatihan" } },
  { hanzi: "外勞就業安定費",   pinyin: "wàiláo jiùyè āndìng fèi", category: "finance-expense-personnel", partOfSpeech: "N", tr: { en: "foreign-worker stabilization fee", th: "ค่าธรรมเนียมแรงงานต่างชาติ",                          vi: "Phí ổn định việc làm lao động NN",                id: "Biaya stabilisasi tenaga kerja asing" } },

  // 🏥 支出科目 - 事務/維護費 / Office & Maintenance (23)
  { hanzi: "事務費",           pinyin: "shìwù fèi",             category: "finance-expense-office", partOfSpeech: "N", tr: { en: "office / business expense",            th: "ค่าใช้จ่ายสำนักงาน",                                 vi: "Chi phí văn phòng",                              id: "Biaya kantor" } },
  { hanzi: "交通費",           pinyin: "jiāotōng fèi",          category: "finance-expense-office", partOfSpeech: "N", tr: { en: "travel / transportation expense",      th: "ค่าเดินทาง",                                       vi: "Chi phí đi lại",                                  id: "Biaya transportasi" } },
  { hanzi: "文具用品",         pinyin: "wénjù yòngpǐn",         category: "finance-expense-office", partOfSpeech: "N", tr: { en: "office stationery",                     th: "ค่าเครื่องเขียน",                                   vi: "Văn phòng phẩm",                                  id: "Alat tulis kantor" } },
  { hanzi: "印刷費",           pinyin: "yìnshuā fèi",           category: "finance-expense-office", partOfSpeech: "N", tr: { en: "printing expense",                       th: "ค่าพิมพ์เอกสาร",                                    vi: "Phí in ấn",                                       id: "Biaya percetakan" } },
  { hanzi: "運費",             pinyin: "yùnfèi",                category: "finance-expense-office", partOfSpeech: "N", tr: { en: "shipping / freight",                     th: "ค่าขนส่ง",                                          vi: "Phí vận chuyển",                                  id: "Biaya pengiriman" } },
  { hanzi: "郵電費",           pinyin: "yóudiàn fèi",           category: "finance-expense-office", partOfSpeech: "N", tr: { en: "postage & telecom",                      th: "ค่าไปรษณีย์และโทรคมนาคม",                            vi: "Phí bưu điện - viễn thông",                      id: "Biaya pos & telekomunikasi" } },
  { hanzi: "交際費",           pinyin: "jiāojì fèi",            category: "finance-expense-office", partOfSpeech: "N", tr: { en: "entertainment expense",                  th: "ค่ารับรอง",                                         vi: "Chi phí giao tế",                                 id: "Biaya entertainment / jamuan" } },
  { hanzi: "書報雜誌",         pinyin: "shū bào zázhì",         category: "finance-expense-office", partOfSpeech: "N", tr: { en: "books & periodicals",                    th: "ค่าหนังสือและวารสาร",                                vi: "Sách báo tạp chí",                                id: "Buku & majalah" } },
  { hanzi: "水費",             pinyin: "shuǐ fèi",              category: "finance-expense-office", partOfSpeech: "N", tr: { en: "water bill",                              th: "ค่าน้ำ",                                            vi: "Tiền nước",                                       id: "Biaya air" } },
  { hanzi: "電費",             pinyin: "diàn fèi",              category: "finance-expense-office", partOfSpeech: "N", tr: { en: "electricity bill",                        th: "ค่าไฟ",                                            vi: "Tiền điện",                                       id: "Biaya listrik" } },
  { hanzi: "瓦斯費",           pinyin: "wǎsī fèi",              category: "finance-expense-office", partOfSpeech: "N", tr: { en: "gas bill",                                 th: "ค่าแก๊ส",                                           vi: "Tiền gas",                                        id: "Biaya gas" } },
  { hanzi: "租金支出",         pinyin: "zūjīn zhīchū",          category: "finance-expense-office", partOfSpeech: "N", tr: { en: "rent expense",                            th: "ค่าเช่า",                                           vi: "Chi phí thuê",                                    id: "Biaya sewa" } },
  { hanzi: "稅捐",             pinyin: "shuìjuān",              category: "finance-expense-office", partOfSpeech: "N", tr: { en: "taxes & duties",                          th: "ค่าภาษี",                                           vi: "Thuế & phí",                                      id: "Pajak & retribusi" } },
  { hanzi: "團體會費",         pinyin: "tuántǐ huìfèi",         category: "finance-expense-office", partOfSpeech: "N", tr: { en: "association membership fees",            th: "ค่าสมาชิกสมาคม",                                    vi: "Phí hội đoàn",                                    id: "Iuran keanggotaan asosiasi" } },
  { hanzi: "募款活動支出",     pinyin: "mùkuǎn huódòng zhīchū", category: "finance-expense-office", partOfSpeech: "N", tr: { en: "fund-raising activity expense",         th: "ค่าใช้จ่ายกิจกรรมระดมทุน",                            vi: "Chi phí hoạt động gây quỹ",                      id: "Biaya kegiatan penggalangan dana" } },
  { hanzi: "設施器具費",       pinyin: "shèshī qìjù fèi",       category: "finance-expense-office", partOfSpeech: "N", tr: { en: "equipment & tools expense",              th: "ค่าอุปกรณ์และเครื่องมือ",                            vi: "Chi phí thiết bị, dụng cụ",                      id: "Biaya peralatan & perangkat" } },
  { hanzi: "雜項購置",         pinyin: "záxiàng gòuzhì",        category: "finance-expense-office", partOfSpeech: "N", tr: { en: "miscellaneous purchases",                th: "ค่าจัดซื้อเบ็ดเตล็ด",                                vi: "Mua sắm linh tinh",                              id: "Pembelian lain-lain" } },
  { hanzi: "維護費",           pinyin: "wéihù fèi",             category: "finance-expense-office", partOfSpeech: "N", tr: { en: "maintenance expense",                    th: "ค่าบำรุงรักษา",                                     vi: "Chi phí bảo trì",                                 id: "Biaya pemeliharaan" } },
  { hanzi: "修繕費",           pinyin: "xiūshàn fèi",           category: "finance-expense-office", partOfSpeech: "N", tr: { en: "repair expense",                          th: "ค่าซ่อมแซม",                                        vi: "Chi phí sửa chữa",                               id: "Biaya perbaikan" } },
  { hanzi: "院舍修繕費",       pinyin: "yuàn shè xiūshàn fèi",  category: "finance-expense-office", partOfSpeech: "N", tr: { en: "facility repair expense",                th: "ค่าซ่อมแซมอาคารบ้านพัก",                              vi: "Chi phí sửa chữa cơ sở",                         id: "Biaya perbaikan gedung wisma" } },
  { hanzi: "公共安全費",       pinyin: "gōnggòng ānquán fèi",   category: "finance-expense-office", partOfSpeech: "N", tr: { en: "public safety expense",                  th: "ค่าความปลอดภัยสาธารณะ",                              vi: "Chi phí an toàn công cộng",                      id: "Biaya keamanan publik" } },
  { hanzi: "折舊",             pinyin: "zhéjiù",                category: "finance-expense-office", partOfSpeech: "N", tr: { en: "depreciation",                            th: "ค่าเสื่อมราคา",                                     vi: "Khấu hao",                                       id: "Penyusutan / Depresiasi" } },
  { hanzi: "各項耗竭及攤提",   pinyin: "gè xiàng hàojié jí tāntí", category: "finance-expense-office", partOfSpeech: "N", tr: { en: "amortization & depletion",          th: "ค่าใช้สิ้นเปลืองและค่าตัดจำหน่าย",                     vi: "Khấu trừ & phân bổ",                             id: "Amortisasi & deplesi" } },

  // 🛡️ 支出科目 - 保險與其他 / Insurance & Other (6)
  { hanzi: "保險退休金",       pinyin: "bǎoxiǎn tuìxiū jīn",    category: "finance-expense-insurance", partOfSpeech: "N", tr: { en: "insurance & pension",                th: "ประกันและเงินบำนาญ",                                vi: "Bảo hiểm & lương hưu",                           id: "Asuransi & pensiun" } },
  { hanzi: "勞健保",           pinyin: "láo jiàn bǎo",          category: "finance-expense-insurance", partOfSpeech: "N", tr: { en: "labor & health insurance",            th: "ประกันแรงงานและประกันสุขภาพ",                          vi: "BHXH & BHYT (Đài Loan)",                          id: "BPJS Tenaga Kerja & Kesehatan" } },
  { hanzi: "勞工退休金",       pinyin: "láogōng tuìxiū jīn",    category: "finance-expense-insurance", partOfSpeech: "N", tr: { en: "labor pension contribution (6%)",     th: "เงินบำนาญแรงงาน",                                  vi: "Quỹ hưu trí lao động",                           id: "Dana pensiun pekerja" } },
  { hanzi: "保險費",           pinyin: "bǎoxiǎn fèi",           category: "finance-expense-insurance", partOfSpeech: "N", tr: { en: "insurance premium",                    th: "ค่าเบี้ยประกัน",                                    vi: "Phí bảo hiểm",                                   id: "Premi asuransi" } },
  { hanzi: "其他成本",         pinyin: "qítā chéngběn",         category: "finance-expense-insurance", partOfSpeech: "N", tr: { en: "other costs",                          th: "ต้นทุนอื่นๆ",                                       vi: "Chi phí khác",                                   id: "Biaya lainnya" } },
  { hanzi: "雜項支出",         pinyin: "záxiàng zhīchū",        category: "finance-expense-insurance", partOfSpeech: "N", tr: { en: "miscellaneous expenses",                th: "ค่าใช้จ่ายเบ็ดเตล็ด",                              vi: "Chi linh tinh",                                   id: "Pengeluaran lain-lain" } },

  // 🍱 支出科目 - 業務/材料費 / Operations & Materials (14)
  { hanzi: "業務費",           pinyin: "yèwù fèi",              category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "operating / business expense",       th: "ค่าใช้จ่ายดำเนินงาน",                               vi: "Chi phí nghiệp vụ",                              id: "Biaya operasional" } },
  { hanzi: "住民活動費",       pinyin: "zhùmín huódòng fèi",    category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "resident activity expense",          th: "ค่ากิจกรรมผู้พักอาศัย",                              vi: "Chi phí hoạt động cư dân",                       id: "Biaya kegiatan penghuni" } },
  { hanzi: "住民交通費",       pinyin: "zhùmín jiāotōng fèi",   category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "resident transport expense",         th: "ค่าเดินทางผู้พักอาศัย",                              vi: "Chi phí đi lại của cư dân",                      id: "Biaya transportasi penghuni" } },
  { hanzi: "材料費",           pinyin: "cáiliào fèi",           category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "materials expense",                    th: "ค่าวัสดุ",                                          vi: "Chi phí vật liệu",                                id: "Biaya bahan / material" } },
  { hanzi: "主副食費",         pinyin: "zhǔ fùshí fèi",         category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "staple & side-dish food cost",         th: "ค่าอาหารหลักและอาหารเสริม",                          vi: "Chi phí thực phẩm chính & phụ",                  id: "Biaya makanan utama & pendamping" } },
  { hanzi: "被服費",           pinyin: "bèifú fèi",             category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "linen & uniform expense",              th: "ค่าเครื่องนอนและเครื่องแบบ",                          vi: "Chi phí ga giường & đồng phục",                  id: "Biaya seprai & seragam" } },
  { hanzi: "住民用品費",       pinyin: "zhùmín yòngpǐn fèi",    category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "resident supplies expense",            th: "ค่าของใช้ผู้พักอาศัย",                                vi: "Chi phí đồ dùng của cư dân",                     id: "Biaya perlengkapan penghuni" } },
  { hanzi: "住民醫藥保健費",   pinyin: "zhùmín yīyào bǎojiàn fèi", category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "resident medical & health expense", th: "ค่ายาและสาธารณสุขผู้พักอาศัย",                       vi: "Chi phí y tế cư dân",                            id: "Biaya kesehatan penghuni" } },
  { hanzi: "住民就醫門診費",   pinyin: "zhùmín jiùyī ménzhěn fèi", category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "resident outpatient expense",      th: "ค่าตรวจรักษาผู้ป่วยนอก",                              vi: "Chi phí khám ngoại trú",                         id: "Biaya rawat jalan" } },
  { hanzi: "醫療耗材",         pinyin: "yīliáo hàocái",         category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "medical consumables",                  th: "วัสดุสิ้นเปลืองทางการแพทย์",                          vi: "Vật tư y tế tiêu hao",                           id: "Bahan habis pakai medis" } },
  { hanzi: "消耗品費",         pinyin: "xiāohào pǐn fèi",       category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "consumables expense",                  th: "ค่าวัสดุสิ้นเปลือง",                                vi: "Chi phí vật tư tiêu hao",                        id: "Biaya bahan habis pakai" } },
  { hanzi: "一般耗材",         pinyin: "yībān hàocái",          category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "general consumables",                  th: "วัสดุสิ้นเปลืองทั่วไป",                              vi: "Vật tư tiêu hao thông thường",                   id: "Bahan habis pakai umum" } },
  { hanzi: "住民營養品",       pinyin: "zhùmín yíngyǎng pǐn",   category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "resident nutrition supplements",      th: "ผลิตภัณฑ์อาหารเสริมผู้พักอาศัย",                       vi: "Thực phẩm bổ sung dinh dưỡng",                   id: "Suplemen gizi penghuni" } },
  { hanzi: "清潔用品",         pinyin: "qīngjié yòngpǐn",       category: "finance-expense-operations", partOfSpeech: "N", tr: { en: "cleaning supplies",                    th: "อุปกรณ์ทำความสะอาด",                                vi: "Đồ dùng vệ sinh",                                id: "Alat kebersihan" } },

  // 📋 行政與分攤 / Administrative & Allocation (6)
  { hanzi: "行政管理支出",     pinyin: "xíngzhèng guǎnlǐ zhīchū", category: "finance-admin-allocation", partOfSpeech: "N", tr: { en: "administrative management expense", th: "ค่าใช้จ่ายในการบริหาร",                              vi: "Chi phí quản lý hành chính",                     id: "Biaya manajemen administrasi" } },
  { hanzi: "目的事業支出",     pinyin: "mùdì shìyè zhīchū",     category: "finance-admin-allocation", partOfSpeech: "N", tr: { en: "purpose-fund expense",                 th: "ค่าใช้จ่ายเพื่อกิจการตามวัตถุประสงค์",                vi: "Chi phí hoạt động theo mục đích",                id: "Biaya kegiatan sesuai tujuan" } },
  { hanzi: "行政作業費",       pinyin: "xíngzhèng zuòyè fèi",   category: "finance-admin-allocation", partOfSpeech: "N", tr: { en: "administrative operations cost",       th: "ค่าธุรการและการดำเนินงาน",                            vi: "Phí tác nghiệp hành chính",                      id: "Biaya operasional administrasi" } },
  { hanzi: "兼任行政總務費",   pinyin: "jiānrèn xíngzhèng zǒngwù fèi", category: "finance-admin-allocation", partOfSpeech: "N", tr: { en: "part-time admin & general-affairs", th: "ค่าธุรการและงานทั่วไป (ส่วนแบ่ง)",                  vi: "Phí kiêm nhiệm hành chính",                       id: "Biaya admin & umum paruh waktu" } },
  { hanzi: "事務器材分攤費",   pinyin: "shìwù qìcái fēntān fèi", category: "finance-admin-allocation", partOfSpeech: "N", tr: { en: "office equipment allocation",       th: "ค่าเฉลี่ยเครื่องมืออุปกรณ์สำนักงาน",                   vi: "Phí phân bổ thiết bị văn phòng",                 id: "Alokasi biaya peralatan kantor" } },
  { hanzi: "分攤",             pinyin: "fēntān",                category: "finance-admin-allocation", partOfSpeech: "N", tr: { en: "allocation / pro-rated share",       th: "การปันส่วน / Allocation",                            vi: "Phân bổ",                                         id: "Alokasi" } },

  // 📈 損益指標 / Profit & Loss (11)
  { hanzi: "餘絀",             pinyin: "yúchù",                 category: "finance-profitloss", partOfSpeech: "N", tr: { en: "surplus / deficit (NPO)",                th: "กำไรขาดทุน (NPO/มูลนิธิ)",                          vi: "Dư - thiếu (NGO)",                                id: "Surplus / defisit (NPO)" } },
  { hanzi: "本期餘(絀)",       pinyin: "běnqí yú (chù)",        category: "finance-profitloss", partOfSpeech: "N", tr: { en: "current-period surplus (deficit)",     th: "กำไร/ขาดทุนงวดนี้",                                vi: "Dư-thiếu kỳ này",                                id: "Surplus/defisit periode ini" } },
  { hanzi: "本期餘絀",         pinyin: "běnqí yúchù",           category: "finance-profitloss", partOfSpeech: "N", tr: { en: "current-period net surplus/deficit", th: "กำไร/ขาดทุนงวดนี้",                                vi: "Dư-thiếu kỳ này",                                id: "Surplus/defisit periode ini" } },
  { hanzi: "盈餘",             pinyin: "yíngyú",                category: "finance-profitloss", partOfSpeech: "N", tr: { en: "surplus / profit",                       th: "กำไร / Surplus",                                  vi: "Thặng dư / Lợi nhuận",                           id: "Surplus / Laba" } },
  { hanzi: "虧損",             pinyin: "kuīsǔn",                category: "finance-profitloss", partOfSpeech: "N", tr: { en: "loss",                                    th: "ขาดทุน",                                          vi: "Lỗ",                                              id: "Rugi" } },
  { hanzi: "支出率",           pinyin: "zhīchū lǜ",             category: "finance-profitloss", partOfSpeech: "N", tr: { en: "expense ratio (cost / income)",         th: "อัตราส่วนรายจ่าย",                                  vi: "Tỷ lệ chi phí",                                  id: "Rasio biaya" } },
  { hanzi: "餘絀率",           pinyin: "yúchù lǜ",              category: "finance-profitloss", partOfSpeech: "N", tr: { en: "surplus/deficit ratio",                  th: "อัตรากำไรขาดทุน",                                  vi: "Tỷ lệ dư-thiếu",                                  id: "Rasio surplus/defisit" } },
  { hanzi: "預算",             pinyin: "yùsuàn",                category: "finance-profitloss", partOfSpeech: "N", tr: { en: "budget",                                  th: "งบประมาณ",                                        vi: "Ngân sách",                                       id: "Anggaran" } },
  { hanzi: "預估",             pinyin: "yùgū",                  category: "finance-profitloss", partOfSpeech: "N", tr: { en: "forecast / estimate",                    th: "ประมาณการ",                                       vi: "Dự kiến / ước tính",                              id: "Estimasi / proyeksi" } },
  { hanzi: "暫估",             pinyin: "zàn gū",                category: "finance-profitloss", partOfSpeech: "N", tr: { en: "preliminary estimate",                   th: "ประมาณการชั่วคราว",                                vi: "Ước tính tạm thời",                              id: "Estimasi sementara" } },
  { hanzi: "精準收入",         pinyin: "jīngzhǔn shōurù",       category: "finance-profitloss", partOfSpeech: "N", tr: { en: "finalized income",                       th: "รายรับที่แม่นยำ (final)",                            vi: "Doanh thu chính xác",                            id: "Pendapatan final / akurat" } },

  // 🏠 折舊資料表欄位 / Depreciation Sheet Fields (28)
  { hanzi: "資產編號",         pinyin: "zīchǎn biānhào",        category: "finance-depreciation", partOfSpeech: "N", tr: { en: "asset code",                               th: "รหัสทรัพย์สิน",                                     vi: "Mã tài sản",                                      id: "Kode aset" } },
  { hanzi: "資產名稱",         pinyin: "zīchǎn míngchēng",      category: "finance-depreciation", partOfSpeech: "N", tr: { en: "asset name",                               th: "ชื่อทรัพย์สิน",                                     vi: "Tên tài sản",                                     id: "Nama aset" } },
  { hanzi: "資產規格",         pinyin: "zīchǎn guīgé",          category: "finance-depreciation", partOfSpeech: "N", tr: { en: "asset specifications",                     th: "สเปคทรัพย์สิน",                                     vi: "Thông số tài sản",                                id: "Spesifikasi aset" } },
  { hanzi: "管理區分",         pinyin: "guǎnlǐ qūfēn",          category: "finance-depreciation", partOfSpeech: "N", tr: { en: "management category",                       th: "หมวดการจัดการ",                                     vi: "Phân loại quản lý",                              id: "Kategori manajemen" } },
  { hanzi: "型態",             pinyin: "xíngtài",               category: "finance-depreciation", partOfSpeech: "N", tr: { en: "type / form",                              th: "ประเภท",                                          vi: "Loại / hình thái",                                id: "Tipe" } },
  { hanzi: "主件",             pinyin: "zhǔ jiàn",              category: "finance-depreciation", partOfSpeech: "N", tr: { en: "main item",                                th: "รายการหลัก",                                       vi: "Hạng mục chính",                                  id: "Item utama" } },
  { hanzi: "主件編號",         pinyin: "zhǔ jiàn biānhào",      category: "finance-depreciation", partOfSpeech: "N", tr: { en: "main item code",                            th: "รหัสรายการหลัก",                                    vi: "Mã hạng mục chính",                              id: "Kode item utama" } },
  { hanzi: "取得日期",         pinyin: "qǔdé rìqí",             category: "finance-depreciation", partOfSpeech: "N", tr: { en: "acquisition date",                          th: "วันที่ได้มา",                                       vi: "Ngày mua sắm",                                    id: "Tanggal perolehan" } },
  { hanzi: "取得成本",         pinyin: "qǔdé chéngběn",         category: "finance-depreciation", partOfSpeech: "N", tr: { en: "acquisition cost",                          th: "ต้นทุนการได้มา",                                    vi: "Giá mua",                                         id: "Biaya perolehan" } },
  { hanzi: "原幣取得成本",     pinyin: "yuán bì qǔdé chéngběn", category: "finance-depreciation", partOfSpeech: "N", tr: { en: "acquisition cost (original currency)",   th: "ต้นทุนการได้มา (สกุลเดิม)",                          vi: "Giá mua (nguyên tệ)",                            id: "Biaya perolehan (mata uang asal)" } },
  { hanzi: "銷帳日期",         pinyin: "xiāo zhàng rìqí",       category: "finance-depreciation", partOfSpeech: "N", tr: { en: "write-off date",                            th: "วันที่ตัดบัญชี",                                    vi: "Ngày xóa sổ",                                     id: "Tanggal hapus buku" } },
  { hanzi: "開始提列",         pinyin: "kāishǐ tí liè",         category: "finance-depreciation", partOfSpeech: "N", tr: { en: "depreciation start date",                  th: "เริ่มคิดค่าเสื่อม",                                  vi: "Bắt đầu trích khấu hao",                          id: "Mulai penyusutan" } },
  { hanzi: "折舊方法",         pinyin: "zhéjiù fāngfǎ",         category: "finance-depreciation", partOfSpeech: "N", tr: { en: "depreciation method",                       th: "วิธีคิดค่าเสื่อม",                                  vi: "Phương pháp khấu hao",                           id: "Metode penyusutan" } },
  { hanzi: "平均法",           pinyin: "píngjūn fǎ",            category: "finance-depreciation", partOfSpeech: "N", tr: { en: "straight-line method",                      th: "วิธีเส้นตรง",                                       vi: "Phương pháp đường thẳng",                         id: "Metode garis lurus" } },
  { hanzi: "耐用年限",         pinyin: "nàiyòng niánxiàn",      category: "finance-depreciation", partOfSpeech: "N", tr: { en: "useful life (years)",                       th: "อายุการใช้งาน (ปี)",                                 vi: "Thời gian sử dụng (năm)",                         id: "Masa manfaat (tahun)" } },
  { hanzi: "未用年限",         pinyin: "wèi yòng niánxiàn",     category: "finance-depreciation", partOfSpeech: "N", tr: { en: "remaining useful life",                     th: "อายุการใช้งานคงเหลือ",                              vi: "Thời gian sử dụng còn lại",                       id: "Sisa masa manfaat" } },
  { hanzi: "預留殘值",         pinyin: "yùliú cánzhí",          category: "finance-depreciation", partOfSpeech: "N", tr: { en: "salvage / residual value",                  th: "มูลค่าซาก",                                         vi: "Giá trị thu hồi",                                id: "Nilai sisa / residu" } },
  { hanzi: "資產價值",         pinyin: "zīchǎn jiàzhí",         category: "finance-depreciation", partOfSpeech: "N", tr: { en: "asset value",                              th: "มูลค่าทรัพย์สิน",                                   vi: "Giá trị tài sản",                                id: "Nilai aset" } },
  { hanzi: "本期提列折舊",     pinyin: "běnqí tí liè zhéjiù",   category: "finance-depreciation", partOfSpeech: "N", tr: { en: "current-period depreciation",              th: "ค่าเสื่อมราคางวดนี้",                                vi: "Khấu hao kỳ này",                                 id: "Penyusutan periode ini" } },
  { hanzi: "累積折舊",         pinyin: "lěijī zhéjiù",          category: "finance-depreciation", partOfSpeech: "N", tr: { en: "accumulated depreciation",                  th: "ค่าเสื่อมราคาสะสม",                                vi: "Khấu hao lũy kế",                                id: "Akumulasi penyusutan" } },
  { hanzi: "帳面價值",         pinyin: "zhàngmiàn jiàzhí",      category: "finance-depreciation", partOfSpeech: "N", tr: { en: "book value",                                th: "มูลค่าตามบัญชี",                                    vi: "Giá trị sổ sách",                                id: "Nilai buku" } },
  { hanzi: "折舊分攤方式",     pinyin: "zhéjiù fēntān fāngshì", category: "finance-depreciation", partOfSpeech: "N", tr: { en: "depreciation allocation method",            th: "วิธีเฉลี่ยค่าเสื่อม",                                vi: "Cách phân bổ khấu hao",                          id: "Metode alokasi penyusutan" } },
  { hanzi: "依保管部門",       pinyin: "yī bǎoguǎn bùmén",      category: "finance-depreciation", partOfSpeech: "N", tr: { en: "by custodian department",                   th: "ตามแผนกที่ดูแล",                                    vi: "Theo phòng ban quản lý",                          id: "Berdasarkan dept. penanggung jawab" } },
  { hanzi: "續提殘值",         pinyin: "xù tí cánzhí",          category: "finance-depreciation", partOfSpeech: "N", tr: { en: "continued residual value",                  th: "มูลค่าซากที่คิดต่อ",                                vi: "Giá trị thu hồi tiếp tục",                       id: "Nilai sisa lanjutan" } },
  { hanzi: "續提耐用月數",     pinyin: "xù tí nàiyòng yuè shù", category: "finance-depreciation", partOfSpeech: "N", tr: { en: "continued useful months",                   th: "จำนวนเดือนที่คิดต่อ",                                vi: "Số tháng sử dụng tiếp",                          id: "Bulan masa manfaat lanjutan" } },
  { hanzi: "數量",             pinyin: "shùliàng",              category: "finance-depreciation", partOfSpeech: "N", tr: { en: "quantity",                                  th: "จำนวน",                                            vi: "Số lượng",                                        id: "Jumlah" } },
  { hanzi: "單位",             pinyin: "dānwèi",                category: "finance-depreciation", partOfSpeech: "N", tr: { en: "unit",                                       th: "หน่วย",                                            vi: "Đơn vị",                                          id: "Satuan" } },
  { hanzi: "備註",             pinyin: "bèizhù",                category: "finance-depreciation", partOfSpeech: "N", tr: { en: "remarks / notes",                            th: "หมายเหตุ",                                         vi: "Ghi chú",                                         id: "Catatan" } },

  // 🔢 量詞與時間 / Measure Words & Time (9)
  { hanzi: "式",               pinyin: "shì",                   category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) set / system",                        th: "(ลักษณนาม) ชุด/ระบบ",                                vi: "(LT) bộ / hệ thống",                              id: "(KB) set / sistem" } },
  { hanzi: "組",               pinyin: "zǔ",                    category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) set",                                  th: "(ลักษณนาม) ชุด",                                     vi: "(LT) bộ / nhóm",                                  id: "(KB) set" } },
  { hanzi: "套",               pinyin: "tào",                   category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) suite / kit",                          th: "(ลักษณนาม) ชุด / suite",                            vi: "(LT) bộ / suite",                                 id: "(KB) set / paket" } },
  { hanzi: "台",               pinyin: "tái",                   category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) machines / appliances",                th: "(ลักษณนาม) เครื่อง",                                  vi: "(LT) chiếc (máy)",                                id: "(KB) unit (mesin)" } },
  { hanzi: "輛",               pinyin: "liàng",                 category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) vehicles",                              th: "(ลักษณนาม) คัน (รถ)",                                vi: "(LT) chiếc (xe)",                                 id: "(KB) unit (kendaraan)" } },
  { hanzi: "個",               pinyin: "gè",                    category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) generic / one",                         th: "(ลักษณนาม) อัน/ชิ้น",                                vi: "(LT) cái",                                         id: "(KB) buah / unit" } },
  { hanzi: "張",               pinyin: "zhāng",                 category: "finance-measure", partOfSpeech: "M", tr: { en: "(M) flat objects",                          th: "(ลักษณนาม) แผ่น/ตัว",                                vi: "(LT) tờ / chiếc (vật phẳng)",                     id: "(KB) lembar / buah datar" } },
  { hanzi: "萬",               pinyin: "wàn",                   category: "finance-measure", partOfSpeech: "M", tr: { en: "10,000 (ten thousand)",                     th: "หมื่น (10,000)",                                    vi: "Vạn (10.000)",                                    id: "Sepuluh ribu (10.000)" } },
  { hanzi: "元",               pinyin: "yuán",                  category: "finance-measure", partOfSpeech: "N", tr: { en: "yuan / NT$ (TWD)",                          th: "ดอลลาร์ (TWD)",                                     vi: "đô la Đài Loan",                                  id: "Dolar Taiwan (TWD)" } },

  // 🛏️ 設備資產名稱 / Equipment & Assets (33)
  { hanzi: "裝修工程",         pinyin: "zhuāngxiū gōngchéng",   category: "finance-equipment", partOfSpeech: "N", tr: { en: "renovation works",                          th: "งานตกแต่ง",                                         vi: "Công trình trang trí nội thất",                   id: "Pekerjaan renovasi" } },
  { hanzi: "資訊系統",         pinyin: "zīxùn xìtǒng",          category: "finance-equipment", partOfSpeech: "N", tr: { en: "IT / information system",                   th: "ระบบสารสนเทศ",                                      vi: "Hệ thống CNTT",                                  id: "Sistem informasi / TI" } },
  { hanzi: "硬體設備",         pinyin: "yìngtǐ shèbèi",         category: "finance-equipment", partOfSpeech: "N", tr: { en: "hardware equipment",                        th: "อุปกรณ์ฮาร์ดแวร์",                                  vi: "Thiết bị phần cứng",                             id: "Perangkat keras" } },
  { hanzi: "臉部辨識系統",     pinyin: "liǎn bù biànshí xìtǒng", category: "finance-equipment", partOfSpeech: "N", tr: { en: "facial-recognition system",                th: "ระบบจดจำใบหน้า",                                     vi: "Hệ thống nhận diện khuôn mặt",                   id: "Sistem pengenalan wajah" } },
  { hanzi: "投影機",           pinyin: "tóuyǐng jī",            category: "finance-equipment", partOfSpeech: "N", tr: { en: "projector",                                  th: "เครื่องโปรเจคเตอร์",                                vi: "Máy chiếu",                                       id: "Proyektor" } },
  { hanzi: "電視機",           pinyin: "diànshì jī",            category: "finance-equipment", partOfSpeech: "N", tr: { en: "television",                                 th: "โทรทัศน์",                                          vi: "TV",                                              id: "Televisi" } },
  { hanzi: "擴音機",           pinyin: "kuòyīn jī",             category: "finance-equipment", partOfSpeech: "N", tr: { en: "amplifier / PA system",                      th: "เครื่องขยายเสียง",                                  vi: "Loa khuếch đại",                                  id: "Amplifier / pengeras suara" } },
  { hanzi: "液晶螢幕",         pinyin: "yèjīng yíngmù",         category: "finance-equipment", partOfSpeech: "N", tr: { en: "LCD monitor",                                th: "จอ LCD",                                            vi: "Màn hình LCD",                                    id: "Monitor LCD" } },
  { hanzi: "壁掛桌機",         pinyin: "bìguà zhuō jī",         category: "finance-equipment", partOfSpeech: "N", tr: { en: "wall-mounted desktop PC",                    th: "คอมพิวเตอร์ติดผนัง",                                vi: "Máy tính treo tường",                            id: "PC dinding" } },
  { hanzi: "空氣品質監測",     pinyin: "kōngqì pǐnzhí jiāncè",  category: "finance-equipment", partOfSpeech: "N", tr: { en: "air-quality monitor",                        th: "ตรวจสอบคุณภาพอากาศ",                                vi: "Giám sát chất lượng không khí",                   id: "Pemantau kualitas udara" } },
  { hanzi: "車輛追蹤管理",     pinyin: "chēliàng zhuīzōng guǎnlǐ", category: "finance-equipment", partOfSpeech: "N", tr: { en: "vehicle tracking management",        th: "ระบบติดตามและจัดการยานพาหนะ",                          vi: "Quản lý theo dõi xe",                            id: "Sistem pelacak kendaraan" } },
  { hanzi: "蒸烤箱",           pinyin: "zhēng kǎoxiāng",        category: "finance-equipment", partOfSpeech: "N", tr: { en: "steam oven",                                 th: "เตาอบไอน้ำ",                                        vi: "Lò hấp nướng",                                    id: "Oven uap" } },
  { hanzi: "生命徵象量測",     pinyin: "shēngmìng zhēngxiàng liángcè", category: "finance-equipment", partOfSpeech: "N", tr: { en: "vital-signs monitor",            th: "เครื่องวัดสัญญาณชีพ",                                vi: "Máy đo dấu hiệu sinh tồn",                       id: "Alat ukur tanda vital" } },
  { hanzi: "換藥車",           pinyin: "huànyào chē",           category: "finance-equipment", partOfSpeech: "N", tr: { en: "medication trolley",                          th: "รถเข็นเปลี่ยนยา",                                  vi: "Xe đẩy phát thuốc",                              id: "Troli ganti obat" } },
  { hanzi: "座椅式體重機",     pinyin: "zuòyǐ shì tǐzhòng jī",  category: "finance-equipment", partOfSpeech: "N", tr: { en: "seated weighing machine",                    th: "เครื่องชั่งน้ำหนักแบบเก้าอี้",                       vi: "Máy cân ngồi (cho người già)",                   id: "Timbangan duduk" } },
  { hanzi: "上肢復健器材",     pinyin: "shàngzhī fùjiàn qìcái", category: "finance-equipment", partOfSpeech: "N", tr: { en: "upper-limb rehab equipment",                 th: "อุปกรณ์กายภาพบำบัดส่วนบน",                            vi: "Thiết bị phục hồi chi trên",                     id: "Alat rehabilitasi tubuh atas" } },
  { hanzi: "餐桌",             pinyin: "cānzhuō",               category: "finance-equipment", partOfSpeech: "N", tr: { en: "dining table",                                th: "โต๊ะรับประทานอาหาร",                                vi: "Bàn ăn",                                          id: "Meja makan" } },
  { hanzi: "長桌",             pinyin: "cháng zhuō",            category: "finance-equipment", partOfSpeech: "N", tr: { en: "long table",                                  th: "โต๊ะยาว",                                          vi: "Bàn dài",                                         id: "Meja panjang" } },
  { hanzi: "圓桌",             pinyin: "yuán zhuō",             category: "finance-equipment", partOfSpeech: "N", tr: { en: "round table",                                 th: "โต๊ะกลม",                                          vi: "Bàn tròn",                                        id: "Meja bundar" } },
  { hanzi: "扶手餐椅",         pinyin: "fúshǒu cān yǐ",         category: "finance-equipment", partOfSpeech: "N", tr: { en: "armchair / dining chair w/ arms",            th: "เก้าอี้รับประทานอาหารมีที่วางแขน",                    vi: "Ghế ăn có tay vịn",                              id: "Kursi makan dengan sandaran tangan" } },
  { hanzi: "沙發",             pinyin: "shāfā",                 category: "finance-equipment", partOfSpeech: "N", tr: { en: "sofa",                                        th: "โซฟา",                                             vi: "Sofa",                                            id: "Sofa" } },
  { hanzi: "飲水機",           pinyin: "yǐnshuǐ jī",            category: "finance-equipment", partOfSpeech: "N", tr: { en: "water dispenser",                             th: "เครื่องทำน้ำดื่ม",                                  vi: "Máy lọc nước uống",                              id: "Dispenser air minum" } },
  { hanzi: "洗碗機",           pinyin: "xǐwǎn jī",              category: "finance-equipment", partOfSpeech: "N", tr: { en: "dishwasher",                                  th: "เครื่องล้างจาน",                                   vi: "Máy rửa chén",                                    id: "Mesin pencuci piring" } },
  { hanzi: "崁入式",           pinyin: "qiàn rù shì",           category: "finance-equipment", partOfSpeech: "N", tr: { en: "built-in",                                    th: "แบบฝัง",                                          vi: "Âm tủ / âm tường",                                id: "Built-in / tertanam" } },
  { hanzi: "變頻冰箱",         pinyin: "biànpín bīngxiāng",     category: "finance-equipment", partOfSpeech: "N", tr: { en: "inverter refrigerator",                       th: "ตู้เย็นระบบอินเวอร์เตอร์",                            vi: "Tủ lạnh inverter",                               id: "Kulkas inverter" } },
  { hanzi: "空調設備",         pinyin: "kòngtiáo shèbèi",       category: "finance-equipment", partOfSpeech: "N", tr: { en: "HVAC equipment",                              th: "เครื่องปรับอากาศ",                                  vi: "Thiết bị điều hòa",                              id: "Peralatan HVAC / pendingin" } },
  { hanzi: "分離式冷氣機",     pinyin: "fēnlí shì lěngqì jī",   category: "finance-equipment", partOfSpeech: "N", tr: { en: "split-type air conditioner",                  th: "แอร์รุ่นแยกส่วน",                                  vi: "Điều hòa kiểu rời",                              id: "AC split" } },
  { hanzi: "休閒藤椅",         pinyin: "xiūxián téng yǐ",       category: "finance-equipment", partOfSpeech: "N", tr: { en: "rattan lounge chair",                          th: "เก้าอี้หวายพักผ่อน",                              vi: "Ghế mây thư giãn",                                id: "Kursi rotan santai" } },
  { hanzi: "休閒躺椅",         pinyin: "xiūxián tǎng yǐ",       category: "finance-equipment", partOfSpeech: "N", tr: { en: "lounge / recliner chair",                     th: "เก้าอี้เอนพักผ่อน",                                vi: "Ghế ngả thư giãn",                                id: "Kursi santai / recliner" } },
  { hanzi: "印柚集成桌組",     pinyin: "yìn yòu jíchéng zhuō zǔ", category: "finance-equipment", partOfSpeech: "N", tr: { en: "Burmese teak table set",                    th: "ชุดโต๊ะรวมไม้สัก (พม่า)",                            vi: "Bộ bàn gỗ tếch Miến Điện",                       id: "Set meja jati Burma" } },
  { hanzi: "不斷電系統",       pinyin: "bùduàn diàn xìtǒng",    category: "finance-equipment", partOfSpeech: "N", tr: { en: "uninterruptible power supply (UPS)",          th: "ระบบ UPS",                                          vi: "Hệ thống UPS",                                    id: "UPS / catu daya tak terputus" } },
  { hanzi: "灌溉系統",         pinyin: "guàngài xìtǒng",        category: "finance-equipment", partOfSpeech: "N", tr: { en: "irrigation system",                            th: "ระบบรดน้ำ",                                          vi: "Hệ thống tưới",                                  id: "Sistem irigasi" } },
  { hanzi: "影印機",           pinyin: "yǐngyìn jī",            category: "finance-equipment", partOfSpeech: "N", tr: { en: "photocopier",                                  th: "เครื่องถ่ายเอกสาร",                                vi: "Máy photocopy",                                  id: "Mesin fotokopi" } },

  // 📝 補助 / 業務常用詞 / Subsidy & Business Common (18)
  { hanzi: "長輩",             pinyin: "zhǎngbèi",              category: "finance-misc", partOfSpeech: "N", tr: { en: "elder (respectful term)",                    th: "ผู้สูงอายุ (เรียกอย่างให้เกียรติ)",                      vi: "Bậc cao niên (kính ngữ)",                        id: "Lansia (sebutan hormat)" } },
  { hanzi: "住民",             pinyin: "zhùmín",                category: "finance-misc", partOfSpeech: "N", tr: { en: "resident",                                    th: "ผู้พักอาศัย",                                       vi: "Cư dân / người cư trú",                          id: "Penghuni" } },
  { hanzi: "入住",             pinyin: "rùzhù",                 category: "finance-misc", partOfSpeech: "V", tr: { en: "to move in / check-in",                       th: "ย้ายเข้า / Check-in",                                vi: "Nhập viện / nhận chỗ ở",                         id: "Masuk / check-in" } },
  { hanzi: "床位",             pinyin: "chuáng wèi",            category: "finance-misc", partOfSpeech: "N", tr: { en: "bed / number of beds",                        th: "เตียง / จำนวนเตียง",                                vi: "Giường (số giường)",                              id: "Tempat tidur / kapasitas" } },
  { hanzi: "床頭卡",           pinyin: "chuáng tóu kǎ",         category: "finance-misc", partOfSpeech: "N", tr: { en: "bedhead card / patient card",                 th: "ป้ายหัวเตียง",                                      vi: "Bảng đầu giường",                                id: "Kartu kepala tempat tidur" } },
  { hanzi: "床墊",             pinyin: "chuáng diàn",           category: "finance-misc", partOfSpeech: "N", tr: { en: "mattress",                                     th: "ที่นอน",                                            vi: "Đệm",                                             id: "Kasur" } },
  { hanzi: "照服員",           pinyin: "zhào fú yuán",          category: "finance-misc", partOfSpeech: "N", tr: { en: "caregiver",                                    th: "ผู้ดูแล",                                           vi: "Nhân viên chăm sóc",                             id: "Pengasuh / caregiver" } },
  { hanzi: "進階培訓",         pinyin: "jìnjiē péixùn",         category: "finance-misc", partOfSpeech: "N", tr: { en: "advanced training",                            th: "การฝึกอบรมขั้นสูง",                                vi: "Đào tạo nâng cao",                                id: "Pelatihan lanjutan" } },
  { hanzi: "獎勵金",           pinyin: "jiǎnglì jīn",           category: "finance-misc", partOfSpeech: "N", tr: { en: "incentive / reward bonus",                    th: "เงินรางวัล",                                        vi: "Tiền thưởng khích lệ",                           id: "Insentif / bonus" } },
  { hanzi: "服務天數",         pinyin: "fúwù tiānshù",          category: "finance-misc", partOfSpeech: "N", tr: { en: "service days",                                  th: "จำนวนวันให้บริการ",                                vi: "Số ngày phục vụ",                                id: "Jumlah hari layanan" } },
  { hanzi: "服務人次",         pinyin: "fúwù réncì",            category: "finance-misc", partOfSpeech: "N", tr: { en: "service man-times (visit count)",             th: "จำนวนครั้งที่ให้บริการ (man-times)",                  vi: "Lượt phục vụ",                                    id: "Jumlah kali pelayanan" } },
  { hanzi: "預計",             pinyin: "yùjì",                  category: "finance-misc", partOfSpeech: "Adv", tr: { en: "expected / projected",                       th: "คาดการณ์",                                         vi: "Dự kiến",                                         id: "Diperkirakan" } },
  { hanzi: "實際",             pinyin: "shíjì",                 category: "finance-misc", partOfSpeech: "Adv", tr: { en: "actual",                                     th: "จริง",                                              vi: "Thực tế",                                        id: "Aktual / sebenarnya" } },
  { hanzi: "收費",             pinyin: "shōufèi",               category: "finance-misc", partOfSpeech: "V", tr: { en: "to charge a fee",                              th: "ค่าธรรมเนียม",                                      vi: "Thu phí",                                         id: "Biaya / memungut biaya" } },
  { hanzi: "調漲",             pinyin: "tiáo zhǎng",            category: "finance-misc", partOfSpeech: "V", tr: { en: "to raise (price/fee)",                          th: "ปรับขึ้น (ราคา)",                                  vi: "Điều chỉnh tăng",                                id: "Menaikkan (harga)" } },
  { hanzi: "春酒",             pinyin: "chūnjiǔ",               category: "finance-misc", partOfSpeech: "N", tr: { en: "Lunar New Year company banquet",              th: "งานเลี้ยงตรุษจีน",                                  vi: "Tiệc đầu năm",                                    id: "Pesta tahun baru imlek perusahaan" } },
  { hanzi: "頂樓",             pinyin: "dǐnglóu",               category: "finance-misc", partOfSpeech: "N", tr: { en: "rooftop / top floor",                          th: "ดาดฟ้า",                                            vi: "Sân thượng",                                      id: "Atap / lantai atas" } },
  { hanzi: "現金支出",         pinyin: "xiànjīn zhīchū",        category: "finance-misc", partOfSpeech: "N", tr: { en: "cash expense",                                  th: "รายจ่ายที่เป็นเงินสด",                              vi: "Chi tiền mặt",                                    id: "Pengeluaran tunai" } },
];

async function main() {
  console.log(`📚 Seeding ${ROWS.length} finance vocabulary entries…`);
  const counts: Record<string, number> = {};

  for (const r of ROWS) {
    counts[r.category] = (counts[r.category] ?? 0) + 1;
    await db.vocabulary.upsert({
      where: { hanzi: r.hanzi },
      create: {
        hanzi: r.hanzi,
        zhuyin: r.pinyin,
        pinyin: r.pinyin,
        partOfSpeech: r.partOfSpeech ?? "N",
        translations: { en: r.tr.en, th: r.tr.th, vi: r.tr.vi, id: r.tr.id },
        level: Level.B1_INTERMEDIATE,
        tocflBand: "B1",
        frequency: 3,
        difficulty: 3,
        category: r.category,
        tags: ["b1", "finance", "eldercare", "workplace", r.category],
        isEldercareVocab: true,
      },
      update: {
        pinyin: r.pinyin,
        partOfSpeech: r.partOfSpeech ?? "N",
        translations: { en: r.tr.en, th: r.tr.th, vi: r.tr.vi, id: r.tr.id },
        category: r.category,
        tags: ["b1", "finance", "eldercare", "workplace", r.category],
        isEldercareVocab: true,
      },
    });
  }

  console.log(`\n✅ Seeded:`);
  for (const [cat, n] of Object.entries(counts)) {
    console.log(`   ${cat.padEnd(30)} ${n}`);
  }
  console.log(`   ${"TOTAL".padEnd(30)} ${ROWS.length}`);

  await db.$disconnect();
}

main().catch((err) => { console.error(err); process.exit(1); });
